<a href="https://colab.research.google.com/github/mxls34/AdvanceDatabase/blob/main/Chapter2_HW_SQL_Selection_and_Complex_Conditions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

รหัสนักศึกษา:6706021612143

ชื่อ-สกุล:นาย ณัฐกรณ์ มะลิซ้อน

# การบ้าน Chapter 2: SQL Selection and Complex Conditions
## Mini Case Study — ทำความสะอาดข้อมูลร้านหนังสือออนไลน์ "อ่านเพลิน"

**คำชี้แจง:**
ร้านหนังสือออนไลน์ "อ่านเพลิน" ส่งข้อมูลลูกค้าและคำสั่งซื้อมาให้คุณในฐานะ Data Analyst
แต่ข้อมูลชุดนี้ **ยังไม่ได้ทำความสะอาด** ซึ่งในข้อมูลจะมีทั้ง ค่าว่าง (NULL) ค่าที่ผิดปกติ และรูปแบบที่ไม่สม่ำเสมอปนอยู่

หน้าที่ของคุณคือ ใช้ความรู้จาก Chapter 2 เช่น SELECT & Filtering, Complex Conditions, การจัดการ NULL, Sargable Conditions
เพื่อ **สำรวจ ตรวจสอบ และรายงานปัญหาคุณภาพข้อมูล** ที่พบ พร้อมเขียน query แก้ปัญหาแต่ละจุด

## เตรียมข้อมูล (Setup)
รันเซลล์ด้านล่างเพื่อโหลดฐานข้อมูล `bookstore_customers.duckdb`
ซึ่งมี 2 ตาราง: `customers` (ข้อมูลลูกค้า) และ `orders` (ข้อมูลคำสั่งซื้อ)

In [1]:
import duckdb

con = duckdb.connect('bookstore_customers.duckdb')

# ดูโครงสร้างตารางคร่าว ๆ
print(con.execute("SELECT * FROM customers LIMIT 5").df())
print(con.execute("SELECT * FROM orders LIMIT 5").df())

   customer_id  full_name               email       phone   age       city  \
0            1     สมศรี0                None  0839958838     0  เชียงใหม่
1            2      มาลี1      มาลี1@mail.com        None    47   กรุงเทพฯ
2            3  ประยุทธ์2  ประยุทธ์2@mail.com  0847338124    15     ชลบุรี
3            4      สมพร3       สมพร3mail.com  0823718431  <NA>  เชียงใหม่
4            5    สมหญิง4    สมหญิง4@mail.com  0860806024  <NA>     ภูเก็ต

  signup_date membership_status
0  2024-12-18            active
1  2024-04-23              None
2  2024-07-11            ACTIVE
3  2023-06-20            ACTIVE
4  2024-10-28            ACTIVE
   order_id  customer_id           book_title  quantity  unit_price  \
0         1           15         คิดแบบผู้ชนะ         4      526.25
1         2           35     ประวัติศาสตร์ไทย         1      242.77
2         3           23     ประวัติศาสตร์ไทย         5      542.77
3         4           34  นิยายรักในสวนดอกไม้         1      552.76
4         5           20  คู่มือ Data Science         3      258.96

  order_date discount_code
0 2024-06-21          None
1 2024-01-04          None
2 2023-05-02        SAVE10
3 2024-11-28          None
4 2023-04-14

---
## Part 1: SELECT & Filtering

**1.1** เลือกเฉพาะคอลัมน์ `full_name`, `email`, `city` จากตาราง `customers`
ใช้ alias เปลี่ยนชื่อ `full_name` เป็น `name`

In [ ]:
# TODO 1.1
con.execute("""
      SELECT full_name AS name, email, city FROM customers
""").df()

          name                email        city
0       สมศรี0                 None   เชียงใหม่
1        มาลี1       มาลี1@mail.com    กรุงเทพฯ
2    ประยุทธ์2   ประยุทธ์2@mail.com      ชลบุรี
3        สมพร3        สมพร3mail.com   เชียงใหม่
4      สมหญิง4     สมหญิง4@mail.com      ภูเก็ต
5        มาลี5                           ภูเก็ต
6        สุดา6        สุดา6mail.com  นครราชสีมา
7    สมศักดิ์7   สมศักดิ์7@mail.com    อุดรธานี
8    ประยุทธ์8    ประยุทธ์8mail.com  นครราชสีมา
9        มาลี9       มาลี9@mail.com    อุดรธานี
10  ประยุทธ์10  ประยุทธ์10@mail.com  นครราชสีมา
11  สมศักดิ์11  สมศักดิ์11@mail.com       สงขลา
12   สมบูรณ์12   สมบูรณ์12@mail.com   เชียงใหม่
13      ปิยะ13                 None      ภูเก็ต
14      ธนกร14      ธนกร14@mail.com      ชลบุรี
15      ปิยะ15      ปิยะ15@mail.com      ภูเก็ต
16  สมศักดิ์16                 None      ชลบุรี
17       นภา17        นภา17mail.com     ขอนแก่น
18       กมล18       กมล18@mail.com  นครราชสีมา
19      มาลี19       มาลี19mail.com   เชียงใหม่
20      อรุณ20       อรุณ20mail.com    อุดรธานี
21     วิชัย21                 None    กรุงเทพฯ
22    สมหญิง22    สมหญิง22@mail.com    อุดรธานี
23   วราภรณ์23    วราภรณ์23mail.com   เชียงใหม่
24  สมศักดิ์24  สมศักดิ์24@mail.com     ขอนแก่น
25     สมชาย25     สมชาย25@mail.com    อุดรธานี
26    สมหญิง26    สมหญิง26@mail.com    อุดรธานี
27     รัตนา27                 None     ขอนแก่น
28      มาลี28      มาลี28@mail.com  นครราชสีมา
29      ปิยะ29       ปิยะ29mail.com   เชียงใหม่
30     สมศรี30                 None  นครราชสีมา
31       นภา31       นภา31@mail.com    กรุงเทพฯ
32     สมศรี32     สมศรี32@mail.com   เชียงใหม่
33      ธนกร33      ธนกร33@mail.com      ภูเก็ต
34  สมศักดิ์34  สมศักดิ์34@mail.com      ชลบุรี
35   วราภรณ์35   วราภรณ์35@mail.com      ชลบุรี
36      มาลี36      มาลี36@mail.com    กรุงเทพฯ
37     สมศรี37     สมศรี37@mail.com      ชลบุรี
38    อนันต์38                 None     ขอนแก่น
39     สมศรี39     สมศรี39@mail.com    อุดรธานี

In [ ]:
# ตัวอย่างผลลัพธ์ 1.1

          name                email        city
0       สมศรี0                 None   เชียงใหม่
1        มาลี1       มาลี1@mail.com    กรุงเทพฯ
2    ประยุทธ์2   ประยุทธ์2@mail.com      ชลบุรี
3        สมพร3        สมพร3mail.com   เชียงใหม่
4      สมหญิง4     สมหญิง4@mail.com      ภูเก็ต
5        มาลี5                           ภูเก็ต
6        สุดา6        สุดา6mail.com  นครราชสีมา
7    สมศักดิ์7   สมศักดิ์7@mail.com    อุดรธานี
8    ประยุทธ์8    ประยุทธ์8mail.com  นครราชสีมา
9        มาลี9       มาลี9@mail.com    อุดรธานี
10  ประยุทธ์10  ประยุทธ์10@mail.com  นครราชสีมา
11  สมศักดิ์11  สมศักดิ์11@mail.com       สงขลา
12   สมบูรณ์12   สมบูรณ์12@mail.com   เชียงใหม่
13      ปิยะ13                 None      ภูเก็ต
14      ธนกร14      ธนกร14@mail.com      ชลบุรี
15      ปิยะ15      ปิยะ15@mail.com      ภูเก็ต
16  สมศักดิ์16                 None      ชลบุรี
17       นภา17        นภา17mail.com     ขอนแก่น
18       กมล18       กมล18@mail.com  นครราชสีมา
19      มาลี19       มาลี19mail.com   เชียงใหม่
20      อรุณ20       อรุณ20mail.com    อุดรธานี
21     วิชัย21                 None    กรุงเทพฯ
22    สมหญิง22    สมหญิง22@mail.com    อุดรธานี
23   วราภรณ์23    วราภรณ์23mail.com   เชียงใหม่
24  สมศักดิ์24  สมศักดิ์24@mail.com     ขอนแก่น
25     สมชาย25     สมชาย25@mail.com    อุดรธานี
26    สมหญิง26    สมหญิง26@mail.com    อุดรธานี
27     รัตนา27                 None     ขอนแก่น
28      มาลี28      มาลี28@mail.com  นครราชสีมา
29      ปิยะ29       ปิยะ29mail.com   เชียงใหม่
30     สมศรี30                 None  นครราชสีมา
31       นภา31       นภา31@mail.com    กรุงเทพฯ
32     สมศรี32     สมศรี32@mail.com   เชียงใหม่
33      ธนกร33      ธนกร33@mail.com      ภูเก็ต
34  สมศักดิ์34  สมศักดิ์34@mail.com      ชลบุรี
35   วราภรณ์35   วราภรณ์35@mail.com      ชลบุรี
36      มาลี36      มาลี36@mail.com    กรุงเทพฯ
37     สมศรี37     สมศรี37@mail.com      ชลบุรี
38    อนันต์38                 None     ขอนแก่น
39     สมศรี39     สมศรี39@mail.com    อุดรธานี

**1.2** หาว่าร้านมีลูกค้าอยู่กี่เมือง (city) โดยไม่นับซ้ำ (ใช้ `DISTINCT`)

In [2]:
# TODO 1.2
con.execute("""
    SELECT DISTINCT city FROM customers
""").df()

         city
0   เชียงใหม่
1    กรุงเทพฯ
2    อุดรธานี
3      ชลบุรี
4      ภูเก็ต
5  นครราชสีมา
6       สงขลา
7     ขอนแก่น

In [ ]:
# ตัวอย่างผลลัพธ์ 1.2

         city
0      ชลบุรี
1      ภูเก็ต
2  นครราชสีมา
3       สงขลา
4     ขอนแก่น
5   เชียงใหม่
6    กรุงเทพฯ
7    อุดรธานี

**1.3** เรียงข้อมูลลูกค้าตามอายุ (`age`) จากมากไปน้อย แล้วแสดงเฉพาะ 10 อันดับแรก

In [4]:
# TODO 1.3
con.execute("""
      SELECT * FROM customers ORDER BY age DESC
""").df()

,customer_id,full_name,email,phone,age,city,signup_date,membership_status
0,7,สุดา6,สุดา6mail.com,0858966946,135,นครราชสีมา,2022-11-09,None
1,15,ธนกร14,ธนกร14@mail.com,0836697396,135,ชลบุรี,2024-09-01,Inactive
2,18,นภา17,นภา17mail.com,0866792612,74,ขอนแก่น,2024-05-13,None
3,37,มาลี36,มาลี36@mail.com,0815614174,72,กรุงเทพฯ,2023-04-22,Active
4,10,มาลี9,มาลี9@mail.com,0897971488,71,อุดรธานี,2022-05-05,Active
5,24,วราภรณ์23,วราภรณ์23mail.com,0869476001,69,เชียงใหม่,2022-11-18,active
6,34,ธนกร33,ธนกร33@mail.com,0837326368,69,ภูเก็ต,2024-08-09,active
7,16,ปิยะ15,ปิยะ15@mail.com,None,68,ภูเก็ต,2022-01-08,Inactive
8,32,นภา31,นภา31@mail.com,0850603163,66,กรุงเทพฯ,2024-09-10,None
9,12,สมศักดิ์11,สมศักดิ์11@mail.com,0830514014,65,สงขลา,2024-02-13,inactive
10,6,มาลี5,,None,64,ภูเก็ต,2022-04-28,active
11,38,สมศรี37,สมศรี37@mail.com,0864543049,62,ชลบุรี,2022-03-26,Active
12,26,สมชาย25,สมชาย25@mail.com,0871070189,59,อุดรธานี,2022-04-10,Active
13,28,รัตนา27,None,,58,ขอนแก่น,2023-02-19,Active
14,29,มาลี28,มาลี28@mail.com,0866267415,51,นครราชสีมา,2023-04-22,None
15,17,สมศักดิ์16,None,0819289546,49,ชลบุรี,2022-11-16,Inactive
16,2,มาลี1,มาลี1@mail.com,None,47,กรุงเทพฯ,2024-04-23,None
17,25,สมศักดิ์24,สมศักดิ์24@mail.com,0832321899,45,ขอนแก่น,2023-01-06,inactive
18,22,วิชัย21,None,0857553014,44,กรุงเทพฯ,2024-11-21,active
19,39,อนันต์38,None,0854585178,41,ขอนแก่น,2023-03-26,None
20,11,ประยุทธ์10,ประยุทธ์10@mail.com,0867503414,40,นครราชสีมา,2022-03-17,inactive
21,30,ปิยะ29,ปิยะ29mail.com,0896637649,35,เชียงใหม่,2022-08-20,Inactive
22,20,มาลี19,มาลี19mail.com,None,29,เชียงใหม่,2022-06-03,Inactive
23,23,สมหญิง22,สมหญิง22@mail.com,0824665841,27,อุดรธานี,2022-07-06,ACTIVE
24,40,สมศรี39,สมศรี39@mail.com,None,27,อุดรธานี,2023-05-27,Active
25,8,สมศักดิ์7,สมศักดิ์7@mail.com,,25,อุดรธานี,2023-05-21,None
26,19,กมล18,กมล18@mail.com,0826240908,19,นครราชสีมา,2022-10-18,Active
27,9,ประยุทธ์8,ประยุทธ์8mail.com,0817507864,17,นครราชสีมา,2023-05-03,Active
28,3,ประยุทธ์2,ประยุทธ์2@mail.com,0847338124,15,ชลบุรี,2024-07-11,ACTIVE
29,13,สมบูรณ์12,สมบูรณ์12@mail.com,0884252722,15,เชียงใหม่,2024-09-25,ACTIVE
30,1,สมศรี0,None,0839958838,0,เชียงใหม่,2024-12-18,active
31,21,อรุณ20,อรุณ20mail.com,0882374753,0,อุดรธานี,2022-08-26,inactive
32,31,สมศรี30,None,0845594597,0,นครราชสีมา,2022-04-12,ACTIVE
33,33,สมศรี32,สมศรี32@mail.com,None,0,เชียงใหม่,2024-09-05,ACTIVE
34,36,วราภรณ์35,วราภรณ์35@mail.com,0811297845,0,ชลบุรี,2024-01-27,ACTIVE
35,4,สมพร3,สมพร3mail.com,0823718431,<NA>,เชียงใหม่,2023-06-20,ACTIVE
36,5,สมหญิง4,สมหญิง4@mail.com,0860806024,<NA>,ภูเก็ต,2024-10-28,ACTIVE
37,14,ปิยะ13,None,0870897765,<NA>,ภูเก็ต,2024-03-17,active
38,27,สมหญิง26,สมหญิง26@mail.com,0852091325,<NA>,อุดรธานี,2024-09-06,active
39,35,สมศักดิ์34,สมศักดิ์34@mail.com,0815917225,<NA>,ชลบุรี,2024-05-06,None

In [ ]:
# ตัวอย่างผลลัพธ์ 1.3

,customer_id,full_name,email,phone,age,city,signup_date,membership_status
0,7,สุดา6,สุดา6mail.com,0858966946,135,นครราชสีมา,2022-11-09,None
1,15,ธนกร14,ธนกร14@mail.com,0836697396,135,ชลบุรี,2024-09-01,Inactive
2,18,นภา17,นภา17mail.com,0866792612,74,ขอนแก่น,2024-05-13,None
3,37,มาลี36,มาลี36@mail.com,0815614174,72,กรุงเทพฯ,2023-04-22,Active
4,10,มาลี9,มาลี9@mail.com,0897971488,71,อุดรธานี,2022-05-05,Active
5,24,วราภรณ์23,วราภรณ์23mail.com,0869476001,69,เชียงใหม่,2022-11-18,active
6,34,ธนกร33,ธนกร33@mail.com,0837326368,69,ภูเก็ต,2024-08-09,active
7,16,ปิยะ15,ปิยะ15@mail.com,None,68,ภูเก็ต,2022-01-08,Inactive
8,32,นภา31,นภา31@mail.com,0850603163,66,กรุงเทพฯ,2024-09-10,None
9,12,สมศักดิ์11,สมศักดิ์11@mail.com,0830514014,65,สงขลา,2024-02-13,inactive

**1.4** ต้องการทำ pagination หน้าที่ 2 ของลูกค้าทั้งหมด โดยแสดงหน้าละ 10 คน
(เรียงตาม `customer_id`) เขียน query แสดงข้อมูลของ "หน้าที่ 2"

In [6]:
# TODO 1.4
con.execute("""
      SELECT * FROM customers ORDER BY customer_id ASC LIMIT 10 OFFSET 10
""").df()

,customer_id,full_name,email,phone,age,city,signup_date,membership_status
0,11,ประยุทธ์10,ประยุทธ์10@mail.com,0867503414,40,นครราชสีมา,2022-03-17,inactive
1,12,สมศักดิ์11,สมศักดิ์11@mail.com,0830514014,65,สงขลา,2024-02-13,inactive
2,13,สมบูรณ์12,สมบูรณ์12@mail.com,0884252722,15,เชียงใหม่,2024-09-25,ACTIVE
3,14,ปิยะ13,None,0870897765,<NA>,ภูเก็ต,2024-03-17,active
4,15,ธนกร14,ธนกร14@mail.com,0836697396,135,ชลบุรี,2024-09-01,Inactive
5,16,ปิยะ15,ปิยะ15@mail.com,None,68,ภูเก็ต,2022-01-08,Inactive
6,17,สมศักดิ์16,None,0819289546,49,ชลบุรี,2022-11-16,Inactive
7,18,นภา17,นภา17mail.com,0866792612,74,ขอนแก่น,2024-05-13,None
8,19,กมล18,กมล18@mail.com,0826240908,19,นครราชสีมา,2022-10-18,Active
9,20,มาลี19,มาลี19mail.com,None,29,เชียงใหม่,2022-06-03,Inactive

In [ ]:
# ตัวอย่างผลลัพธ์ 1.4

,customer_id,full_name,email,phone,age,city,signup_date,membership_status
0,11,ประยุทธ์10,ประยุทธ์10@mail.com,0867503414,40,นครราชสีมา,2022-03-17,inactive
1,12,สมศักดิ์11,สมศักดิ์11@mail.com,0830514014,65,สงขลา,2024-02-13,inactive
2,13,สมบูรณ์12,สมบูรณ์12@mail.com,0884252722,15,เชียงใหม่,2024-09-25,ACTIVE
3,14,ปิยะ13,None,0870897765,<NA>,ภูเก็ต,2024-03-17,active
4,15,ธนกร14,ธนกร14@mail.com,0836697396,135,ชลบุรี,2024-09-01,Inactive
5,16,ปิยะ15,ปิยะ15@mail.com,None,68,ภูเก็ต,2022-01-08,Inactive
6,17,สมศักดิ์16,None,0819289546,49,ชลบุรี,2022-11-16,Inactive
7,18,นภา17,นภา17mail.com,0866792612,74,ขอนแก่น,2024-05-13,None
8,19,กมล18,กมล18@mail.com,0826240908,19,นครราชสีมา,2022-10-18,Active
9,20,มาลี19,มาลี19mail.com,None,29,เชียงใหม่,2022-06-03,Inactive

---
## Part 2: Complex Conditions

**2.1** หาลูกค้าที่มีอายุอยู่ในช่วง 18-60 ปี (ใช้ `BETWEEN`)

In [7]:
# TODO 2.1
con.execute("""
      SELECT * FROM customers WHERE age BETWEEN 18 AND 60
""").df()

,customer_id,full_name,email,phone,age,city,signup_date,membership_status
0,2,มาลี1,มาลี1@mail.com,None,47,กรุงเทพฯ,2024-04-23,None
1,8,สมศักดิ์7,สมศักดิ์7@mail.com,,25,อุดรธานี,2023-05-21,None
2,11,ประยุทธ์10,ประยุทธ์10@mail.com,0867503414,40,นครราชสีมา,2022-03-17,inactive
3,17,สมศักดิ์16,None,0819289546,49,ชลบุรี,2022-11-16,Inactive
4,19,กมล18,กมล18@mail.com,0826240908,19,นครราชสีมา,2022-10-18,Active
5,20,มาลี19,มาลี19mail.com,None,29,เชียงใหม่,2022-06-03,Inactive
6,22,วิชัย21,None,0857553014,44,กรุงเทพฯ,2024-11-21,active
7,23,สมหญิง22,สมหญิง22@mail.com,0824665841,27,อุดรธานี,2022-07-06,ACTIVE
8,25,สมศักดิ์24,สมศักดิ์24@mail.com,0832321899,45,ขอนแก่น,2023-01-06,inactive
9,26,สมชาย25,สมชาย25@mail.com,0871070189,59,อุดรธานี,2022-04-10,Active
10,28,รัตนา27,None,,58,ขอนแก่น,2023-02-19,Active
11,29,มาลี28,มาลี28@mail.com,0866267415,51,นครราชสีมา,2023-04-22,None
12,30,ปิยะ29,ปิยะ29mail.com,0896637649,35,เชียงใหม่,2022-08-20,Inactive
13,39,อนันต์38,None,0854585178,41,ขอนแก่น,2023-03-26,None
14,40,สมศรี39,สมศรี39@mail.com,None,27,อุดรธานี,2023-05-27,Active

In [ ]:
# ตัวอย่างผลลัพธ์ 2.1

,customer_id,full_name,email,phone,age,city,signup_date,membership_status
0,2,มาลี1,มาลี1@mail.com,None,47,กรุงเทพฯ,2024-04-23,None
1,8,สมศักดิ์7,สมศักดิ์7@mail.com,,25,อุดรธานี,2023-05-21,None
2,11,ประยุทธ์10,ประยุทธ์10@mail.com,0867503414,40,นครราชสีมา,2022-03-17,inactive
3,17,สมศักดิ์16,None,0819289546,49,ชลบุรี,2022-11-16,Inactive
4,19,กมล18,กมล18@mail.com,0826240908,19,นครราชสีมา,2022-10-18,Active
5,20,มาลี19,มาลี19mail.com,None,29,เชียงใหม่,2022-06-03,Inactive
6,22,วิชัย21,None,0857553014,44,กรุงเทพฯ,2024-11-21,active
7,23,สมหญิง22,สมหญิง22@mail.com,0824665841,27,อุดรธานี,2022-07-06,ACTIVE
8,25,สมศักดิ์24,สมศักดิ์24@mail.com,0832321899,45,ขอนแก่น,2023-01-06,inactive
9,26,สมชาย25,สมชาย25@mail.com,0871070189,59,อุดรธานี,2022-04-10,Active
10,28,รัตนา27,None,,58,ขอนแก่น,2023-02-19,Active
11,29,มาลี28,มาลี28@mail.com,0866267415,51,นครราชสีมา,2023-04-22,None
12,30,ปิยะ29,ปิยะ29mail.com,0896637649,35,เชียงใหม่,2022-08-20,Inactive
13,39,อนันต์38,None,0854585178,41,ขอนแก่น,2023-03-26,None
14,40,สมศรี39,สมศรี39@mail.com,None,27,อุดรธานี,2023-05-27,Active

**2.2** หาลูกค้าที่อยู่ใน "กรุงเทพฯ" หรือ "เชียงใหม่" หรือ "ภูเก็ต" เท่านั้น (ใช้ `IN`)

In [9]:
# TODO 2.2
con.execute("""
        SELECT * FROM customers WHERE city IN ('กรุงเทพฯ', 'ภูเก็ต', 'เชียงใหม่')
""").df()

,customer_id,full_name,email,phone,age,city,signup_date,membership_status
0,1,สมศรี0,None,0839958838,0,เชียงใหม่,2024-12-18,active
1,2,มาลี1,มาลี1@mail.com,None,47,กรุงเทพฯ,2024-04-23,None
2,4,สมพร3,สมพร3mail.com,0823718431,<NA>,เชียงใหม่,2023-06-20,ACTIVE
3,5,สมหญิง4,สมหญิง4@mail.com,0860806024,<NA>,ภูเก็ต,2024-10-28,ACTIVE
4,6,มาลี5,,None,64,ภูเก็ต,2022-04-28,active
5,13,สมบูรณ์12,สมบูรณ์12@mail.com,0884252722,15,เชียงใหม่,2024-09-25,ACTIVE
6,14,ปิยะ13,None,0870897765,<NA>,ภูเก็ต,2024-03-17,active
7,16,ปิยะ15,ปิยะ15@mail.com,None,68,ภูเก็ต,2022-01-08,Inactive
8,20,มาลี19,มาลี19mail.com,None,29,เชียงใหม่,2022-06-03,Inactive
9,22,วิชัย21,None,0857553014,44,กรุงเทพฯ,2024-11-21,active
10,24,วราภรณ์23,วราภรณ์23mail.com,0869476001,69,เชียงใหม่,2022-11-18,active
11,30,ปิยะ29,ปิยะ29mail.com,0896637649,35,เชียงใหม่,2022-08-20,Inactive
12,32,นภา31,นภา31@mail.com,0850603163,66,กรุงเทพฯ,2024-09-10,None
13,33,สมศรี32,สมศรี32@mail.com,None,0,เชียงใหม่,2024-09-05,ACTIVE
14,34,ธนกร33,ธนกร33@mail.com,0837326368,69,ภูเก็ต,2024-08-09,active
15,37,มาลี36,มาลี36@mail.com,0815614174,72,กรุงเทพฯ,2023-04-22,Active

In [ ]:
# ตัวอย่างผลลัพธ์ 2.2

,customer_id,full_name,email,phone,age,city,signup_date,membership_status
0,1,สมศรี0,None,0839958838,0,เชียงใหม่,2024-12-18,active
1,2,มาลี1,มาลี1@mail.com,None,47,กรุงเทพฯ,2024-04-23,None
2,4,สมพร3,สมพร3mail.com,0823718431,<NA>,เชียงใหม่,2023-06-20,ACTIVE
3,5,สมหญิง4,สมหญิง4@mail.com,0860806024,<NA>,ภูเก็ต,2024-10-28,ACTIVE
4,6,มาลี5,,None,64,ภูเก็ต,2022-04-28,active
5,13,สมบูรณ์12,สมบูรณ์12@mail.com,0884252722,15,เชียงใหม่,2024-09-25,ACTIVE
6,14,ปิยะ13,None,0870897765,<NA>,ภูเก็ต,2024-03-17,active
7,16,ปิยะ15,ปิยะ15@mail.com,None,68,ภูเก็ต,2022-01-08,Inactive
8,20,มาลี19,มาลี19mail.com,None,29,เชียงใหม่,2022-06-03,Inactive
9,22,วิชัย21,None,0857553014,44,กรุงเทพฯ,2024-11-21,active
10,24,วราภรณ์23,วราภรณ์23mail.com,0869476001,69,เชียงใหม่,2022-11-18,active
11,30,ปิยะ29,ปิยะ29mail.com,0896637649,35,เชียงใหม่,2022-08-20,Inactive
12,32,นภา31,นภา31@mail.com,0850603163,66,กรุงเทพฯ,2024-09-10,None
13,33,สมศรี32,สมศรี32@mail.com,None,0,เชียงใหม่,2024-09-05,ACTIVE
14,34,ธนกร33,ธนกร33@mail.com,0837326368,69,ภูเก็ต,2024-08-09,active
15,37,มาลี36,มาลี36@mail.com,0815614174,72,กรุงเทพฯ,2023-04-22,Active

**2.3** หาแถวที่ `email` **ไม่มี** เครื่องหมาย `@` อยู่เลย (แสดงว่าอีเมลผิดรูปแบบ)
ใช้ `LIKE` ในการหา

> ระวังไม่ให้ NULL หรือค่าว่าง `''` มาปนในผลลัพธ์ด้วย ลองคิดดูว่าต้องเพิ่มเงื่อนไขอะไรอีก

In [11]:
# TODO 2.3
con.execute("""
      SELECT * FROM customers WHERE email NOt LIKE '%@%'
""").df()

,customer_id,full_name,email,phone,age,city,signup_date,membership_status
0,4,สมพร3,สมพร3mail.com,0823718431,<NA>,เชียงใหม่,2023-06-20,ACTIVE
1,6,มาลี5,,None,64,ภูเก็ต,2022-04-28,active
2,7,สุดา6,สุดา6mail.com,0858966946,135,นครราชสีมา,2022-11-09,None
3,9,ประยุทธ์8,ประยุทธ์8mail.com,0817507864,17,นครราชสีมา,2023-05-03,Active
4,18,นภา17,นภา17mail.com,0866792612,74,ขอนแก่น,2024-05-13,None
5,20,มาลี19,มาลี19mail.com,None,29,เชียงใหม่,2022-06-03,Inactive
6,21,อรุณ20,อรุณ20mail.com,0882374753,0,อุดรธานี,2022-08-26,inactive
7,24,วราภรณ์23,วราภรณ์23mail.com,0869476001,69,เชียงใหม่,2022-11-18,active
8,30,ปิยะ29,ปิยะ29mail.com,0896637649,35,เชียงใหม่,2022-08-20,Inactive

In [ ]:
# ตัวอย่างผลลัพธ์ 2.3

,customer_id,full_name,email,phone,age,city,signup_date,membership_status
0,4,สมพร3,สมพร3mail.com,0823718431,<NA>,เชียงใหม่,2023-06-20,ACTIVE
1,7,สุดา6,สุดา6mail.com,0858966946,135,นครราชสีมา,2022-11-09,None
2,9,ประยุทธ์8,ประยุทธ์8mail.com,0817507864,17,นครราชสีมา,2023-05-03,Active
3,18,นภา17,นภา17mail.com,0866792612,74,ขอนแก่น,2024-05-13,None
4,20,มาลี19,มาลี19mail.com,None,29,เชียงใหม่,2022-06-03,Inactive
5,21,อรุณ20,อรุณ20mail.com,0882374753,0,อุดรธานี,2022-08-26,inactive
6,24,วราภรณ์23,วราภรณ์23mail.com,0869476001,69,เชียงใหม่,2022-11-18,active
7,30,ปิยะ29,ปิยะ29mail.com,0896637649,35,เชียงใหม่,2022-08-20,Inactive

**2.4** ใช้ `CASE` แบ่งกลุ่มลูกค้าตามอายุเป็น 3 กลุ่ม: อายุน้อยกว่า 18 = 'เยาวชน',
18-59 = 'วัยทำงาน', 60 ปีขึ้นไป = 'ผู้สูงอายุ' ตั้งชื่อคอลัมน์ผลลัพธ์ว่า `age_group`

> ให้ลองสังเกตว่าถ้า `age` เป็น NULL ผลลัพธ์ของ CASE จะเป็นอย่างไร (ไปตกที่ ELSE หรือไม่?)

In [13]:
# TODO 2.4
con.execute("""
      SELECT full_name, age,
        CASE
          WHEN age < 18 THEN 'เยาวชน'
          WHEN age < 60 THEN 'วัยทำงาน'
          ELSE 'ผู้สูงอายุ'
        END AS age_group
      FROM customers
""").df()

     full_name   age   age_group
0       สมศรี0     0      เยาวชน
1        มาลี1    47    วัยทำงาน
2    ประยุทธ์2    15      เยาวชน
3        สมพร3  <NA>  ผู้สูงอายุ
4      สมหญิง4  <NA>  ผู้สูงอายุ
5        มาลี5    64  ผู้สูงอายุ
6        สุดา6   135  ผู้สูงอายุ
7    สมศักดิ์7    25    วัยทำงาน
8    ประยุทธ์8    17      เยาวชน
9        มาลี9    71  ผู้สูงอายุ
10  ประยุทธ์10    40    วัยทำงาน
11  สมศักดิ์11    65  ผู้สูงอายุ
12   สมบูรณ์12    15      เยาวชน
13      ปิยะ13  <NA>  ผู้สูงอายุ
14      ธนกร14   135  ผู้สูงอายุ
15      ปิยะ15    68  ผู้สูงอายุ
16  สมศักดิ์16    49    วัยทำงาน
17       นภา17    74  ผู้สูงอายุ
18       กมล18    19    วัยทำงาน
19      มาลี19    29    วัยทำงาน
20      อรุณ20     0      เยาวชน
21     วิชัย21    44    วัยทำงาน
22    สมหญิง22    27    วัยทำงาน
23   วราภรณ์23    69  ผู้สูงอายุ
24  สมศักดิ์24    45    วัยทำงาน
25     สมชาย25    59    วัยทำงาน
26    สมหญิง26  <NA>  ผู้สูงอายุ
27     รัตนา27    58    วัยทำงาน
28      มาลี28    51    วัยทำงาน
29      ปิยะ29    35    วัยทำงาน
30     สมศรี30     0      เยาวชน
31       นภา31    66  ผู้สูงอายุ
32     สมศรี32     0      เยาวชน
33      ธนกร33    69  ผู้สูงอายุ
34  สมศักดิ์34  <NA>  ผู้สูงอายุ
35   วราภรณ์35     0      เยาวชน
36      มาลี36    72  ผู้สูงอายุ
37     สมศรี37    62  ผู้สูงอายุ
38    อนันต์38    41    วัยทำงาน
39     สมศรี39    27    วัยทำงาน

In [ ]:
# ตัวอย่างผลลัพธ์ 2.4

     full_name   age    age_group
0       สมศรี0     0       เยาวชน
1        มาลี1    47     วัยทำงาน
2    ประยุทธ์2    15       เยาวชน
3        สมพร3  <NA>  ไม่ทราบอายุ
4      สมหญิง4  <NA>  ไม่ทราบอายุ
5        มาลี5    64   ผู้สูงอายุ
6        สุดา6   135   ผู้สูงอายุ
7    สมศักดิ์7    25     วัยทำงาน
8    ประยุทธ์8    17       เยาวชน
9        มาลี9    71   ผู้สูงอายุ
10  ประยุทธ์10    40     วัยทำงาน
11  สมศักดิ์11    65   ผู้สูงอายุ
12   สมบูรณ์12    15       เยาวชน
13      ปิยะ13  <NA>  ไม่ทราบอายุ
14      ธนกร14   135   ผู้สูงอายุ
15      ปิยะ15    68   ผู้สูงอายุ
16  สมศักดิ์16    49     วัยทำงาน
17       นภา17    74   ผู้สูงอายุ
18       กมล18    19     วัยทำงาน
19      มาลี19    29     วัยทำงาน
20      อรุณ20     0       เยาวชน
21     วิชัย21    44     วัยทำงาน
22    สมหญิง22    27     วัยทำงาน
23   วราภรณ์23    69   ผู้สูงอายุ
24  สมศักดิ์24    45     วัยทำงาน
25     สมชาย25    59     วัยทำงาน
26    สมหญิง26  <NA>  ไม่ทราบอายุ
27     รัตนา27    58     วัยทำงาน
28      มาลี28    51     วัยทำงาน
29      ปิยะ29    35     วัยทำงาน
30     สมศรี30     0       เยาวชน
31       นภา31    66   ผู้สูงอายุ
32     สมศรี32     0       เยาวชน
33      ธนกร33    69   ผู้สูงอายุ
34  สมศักดิ์34  <NA>  ไม่ทราบอายุ
35   วราภรณ์35     0       เยาวชน
36      มาลี36    72   ผู้สูงอายุ
37     สมศรี37    62   ผู้สูงอายุ
38    อนันต์38    41     วัยทำงาน
39     สมศรี39    27     วัยทำงาน

**2.5** เขียน query เดียวที่รวมเงื่อนไขซับซ้อน: หาลูกค้าที่ (อายุมากกว่า 25 **หรือ** สถานะเป็น active/Active/ACTIVE)
**และ** อยู่ในกรุงเทพฯ เท่านั้น — ใส่วงเล็บให้ถูกต้อง

In [ ]:
# TODO 2.5
con.execute("""

""").df()

In [ ]:
# ตัวอย่างผลลัพธ์ 2.5

,customer_id,full_name,email,phone,age,city,signup_date,membership_status
0,2,มาลี1,มาลี1@mail.com,None,47,กรุงเทพฯ,2024-04-23,None
1,22,วิชัย21,None,0857553014,44,กรุงเทพฯ,2024-11-21,active
2,32,นภา31,นภา31@mail.com,0850603163,66,กรุงเทพฯ,2024-09-10,None
3,37,มาลี36,มาลี36@mail.com,0815614174,72,กรุงเทพฯ,2023-04-22,Active

---
## Part 3: การจัดการ NULL

**3.1** นับจำนวนแถวทั้งหมดในตาราง `customers` เทียบกับจำนวนแถวที่ `email IS NOT NULL`
(ใช้ `COUNT(*)` และ `COUNT(email)` ในคิวรีเดียวกัน) แล้วอธิบายว่าตัวเลขสองค่านี้ต่างกันเพราะอะไร

In [ ]:
# TODO 3.1
con.execute("""

""").df()

_เขียนคำอธิบายตรงนี้:_ ...

In [ ]:
# ตัวอย่างผลลัพธ์ 3.1

   total_rows  non_null_emails
0          40               33

**3.2** ในตาราง `customers` มีค่า `email = NULL` อยู่หรือไม่ ลองรัน query ด้วย `WHERE email = NULL`
แล้วเทียบกับ `WHERE email IS NULL` — ผลลัพธ์ต่างกันหรือไม่? เพราะอะไร

In [ ]:
# TODO 3.2 (ลองทั้งสองแบบ)
con.execute("""

""").df()

_เขียนคำอธิบายตรงนี้:_ ...

In [ ]:
# ตัวอย่างผลลัพธ์ 3.2

ใช้ = NULL ได้: 0
ใช้ IS NULL ได้: 7

**3.3** ใช้ `COALESCE` แสดงเบอร์โทรของลูกค้า โดยถ้า `phone` เป็น NULL หรือค่าว่าง ให้แสดงคำว่า 'ไม่ระบุ' แทน

> `COALESCE` จะจับเฉพาะ NULL เท่านั้น ไม่จับค่าว่าง `''` — ต้องคิดว่าจะจัดการค่าว่างอย่างไรด้วย

In [ ]:
# TODO 3.3
con.execute("""

""").df()

In [ ]:
# ตัวอย่างผลลัพธ์ 3.3

     full_name phone_display
0       สมศรี0    0839958838
1        มาลี1       ไม่ระบุ
2    ประยุทธ์2    0847338124
3        สมพร3    0823718431
4      สมหญิง4    0860806024
5        มาลี5       ไม่ระบุ
6        สุดา6    0858966946
7    สมศักดิ์7       ไม่ระบุ
8    ประยุทธ์8    0817507864
9        มาลี9    0897971488
10  ประยุทธ์10    0867503414
11  สมศักดิ์11    0830514014
12   สมบูรณ์12    0884252722
13      ปิยะ13    0870897765
14      ธนกร14    0836697396
15      ปิยะ15       ไม่ระบุ
16  สมศักดิ์16    0819289546
17       นภา17    0866792612
18       กมล18    0826240908
19      มาลี19       ไม่ระบุ
20      อรุณ20    0882374753
21     วิชัย21    0857553014
22    สมหญิง22    0824665841
23   วราภรณ์23    0869476001
24  สมศักดิ์24    0832321899
25     สมชาย25    0871070189
26    สมหญิง26    0852091325
27     รัตนา27       ไม่ระบุ
28      มาลี28    0866267415
29      ปิยะ29    0896637649
30     สมศรี30    0845594597
31       นภา31    0850603163
32     สมศรี32       ไม่ระบุ
33      ธนกร33    0837326368
34  สมศักดิ์34    0815917225
35   วราภรณ์35    0811297845
36      มาลี36    0815614174
37     สมศรี37    0864543049
38    อนันต์38    0854585178
39     สมศรี39       ไม่ระบุ

---
## Part 4: Sargable Conditions

ในตาราง `orders` มี query ที่เขียนไว้ไม่ดี (non-sargable) ดังนี้

```sql
SELECT * FROM orders
WHERE unit_price / quantity < 100
```

**4.1** อธิบายว่าทำไม query ข้างต้นถึงเป็น non-sargable และอาจมีปัญหาอะไรเพิ่มเติม
(ลองคิดว่าถ้า `quantity` เป็น 0 หรือ NULL จะเกิดอะไรขึ้น)

_เขียนคำอธิบายตรงนี้:_ ...

**4.2** เขียน query ใหม่ให้
1) เป็น sargable มากขึ้น (เงื่อนไขไม่ครอบคอลัมน์ด้วยการคำนวณ)
2) ป้องกันปัญหาการหารด้วยศูนย์หรือค่า NULL ด้วย `NULLIF`

In [ ]:
# TODO 4.2
con.execute("""

""").df()

In [ ]:
# ตัวอย่างผลลัพธ์ 4.2

,order_id,customer_id,book_title,quantity,unit_price,order_date,discount_code,price_per_unit
0,5,20,คู่มือ Data Science,3,258.96,2023-04-14,,86.320000
1,7,38,ประวัติศาสตร์ไทย,4,360.25,2023-11-03,None,90.062500
2,10,25,สอน Python เบื้องต้น,2,122.61,2023-07-08,None,61.305000
3,16,38,คิดแบบผู้ชนะ,5,122.77,2024-05-25,None,24.554000
4,17,27,นิยายรักในสวนดอกไม้,3,133.64,2024-11-22,VIP20,44.546667
5,22,37,นิยายรักในสวนดอกไม้,3,198.86,2023-03-10,None,66.286667
6,24,7,คู่มือ Data Science,5,494.23,2023-06-18,None,98.846000
7,26,24,สอน Python เบื้องต้น,4,365.22,2024-10-26,WELCOME,91.305000
8,28,30,จิตวิทยาการทำงาน,4,205.46,2023-06-26,None,51.365000
9,29,18,คู่มือ Data Science,5,160.24,2024-08-18,VIP20,32.048000
10,31,31,ประวัติศาสตร์ไทย,5,450.34,2024-05-09,None,90.068000
11,35,19,สอน Python เบื้องต้น,3,144.15,2024-02-27,None,48.050000
12,37,27,นิยายรักในสวนดอกไม้,4,328.08,2024-05-19,,82.020000
13,44,3,เศรษฐศาสตร์แบบเข้าใจง่าย,4,205.30,2024-11-27,None,51.325000
14,45,6,สอน Python เบื้องต้น,3,169.16,2023-06-14,,56.386667
15,47,26,คิดแบบผู้ชนะ,5,145.48,2024-10-25,None,29.096000
16,48,29,คิดแบบผู้ชนะ,5,255.37,2024-02-01,VIP20,51.074000
17,50,10,สอน Python เบื้องต้น,3,248.51,2024-08-08,None,82.836667
18,59,7,โลกของโซฟี,3,141.62,2023-05-12,None,47.206667
19,60,10,นิยายรักในสวนดอกไม้,5,204.63,2023-02-20,VIP20,40.926000
20,65,4,สอน Python เบื้องต้น,3,228.16,2024-04-21,None,76.053333
21,68,17,สอน Python เบื้องต้น,3,279.20,2023-08-03,None,93.066667
22,69,15,จิตวิทยาการทำงาน,5,491.62,2023-05-18,None,98.324000
23,70,24,คู่มือ Data Science,3,229.90,2023-10-18,None,76.633333
24,71,40,นิยายรักในสวนดอกไม้,4,262.03,2024-02-05,None,65.507500
25,77,38,นิยายรักในสวนดอกไม้,2,189.35,2023-05-28,SAVE10,94.675000
26,80,24,โลกของโซฟี,2,140.38,2024-08-21,SAVE10,70.190000
27,82,5,เศรษฐศาสตร์แบบเข้าใจง่าย,5,272.84,2024-08-17,,54.568000
28,83,7,โลกของโซฟี,5,221.06,2024-04-14,None,44.212000

---
## สรุป

เขียนสรุปสั้น ๆ (5-8 บรรทัด) ว่าจากการสำรวจข้อมูลทั้งหมด พบปัญหาคุณภาพข้อมูล อะไรบ้างในตาราง `customers` และ `orders` และเสนอแนะว่าก่อนนำข้อมูลนี้ไปใช้วิเคราะห์ต่อ ควรทำความสะอาดอย่างไรบ้าง

_เขียนสรุปตรงนี้:_ ...