<a href="https://colab.research.google.com/github/mxls34/AdvanceDatabase/blob/main/Chapter8_Data_Warehouse_and_Dimensional_Modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 8 Cloud Data Warehouse and Dimensional Modeling with dbt

**หัวข้อ:** CineStar (Movie Theater Chain)

## 0. Setup — เชื่อมต่อฐานข้อมูลและโหลด OLTP Seed Data

ติดตั้งไลบรารีที่ต้องใช้: `psycopg2` สำหรับเชื่อมต่อ PostgreSQL และ `dbt-postgres` สำหรับ dbt

In [2]:
!pip install -q psycopg2-binary dbt-core dbt-postgres pandas

เชื่อมต่อฐานข้อมูล — อ่าน connection string จาก Colab Secrets (`NEON_CONN_STRING`)

In [3]:
import os
import psycopg2
import pandas as pd
from urllib.parse import urlparse

try:
    from google.colab import userdata
    NEON_DSN = userdata.get('NEON_CONNECTION_STRING')
except Exception:
    # fallback สำหรับรันนอก Colab (เช่น ทดสอบ local)
    NEON_DSN = os.environ.get('NEON_CONNECTION_STRING', 'postgresql://postgres:postgres@localhost:5432/cinema_dw')

_u = urlparse(NEON_DSN)
PGHOST, PGPORT = _u.hostname, (_u.port or 5432)
PGUSER, PGPASSWORD = _u.username, _u.password
PGDATABASE = _u.path.lstrip('/')

def run(sql, params=None, fetch=True, retry=True):
    """Execute SQL against Neon Postgres. Retries once on dropped connection
    (Neon serverless can scale-to-zero and drop idle SSL connections)."""
    try:
        with psycopg2.connect(
            host=PGHOST, port=PGPORT, user=PGUSER, password=PGPASSWORD, dbname=PGDATABASE,
            sslmode='require' if PGHOST != 'localhost' else 'prefer',
        ) as conn:
            with conn.cursor() as cur:
                cur.execute(sql, params)
                if fetch and cur.description:
                    cols = [c.name for c in cur.description]
                    return pd.DataFrame(cur.fetchall(), columns=cols)
                conn.commit()
    except psycopg2.OperationalError:
        if retry:
            return run(sql, params, fetch, retry=False)
        raise

run("SELECT version();")

                                             version
0  PostgreSQL 18.6 (6569466) on aarch64-unknown-l...

โหลด OLTP Schema (source system) และ Seed Data ของเครือโรงภาพยนตร์ CineStar

In [ ]:
SEED_SQL = r"""
-- ============================================================
-- Cinema Chain OLTP schema (source system) — Ch.8 Lab
-- ============================================================
DROP TABLE IF EXISTS ticket CASCADE;
DROP TABLE IF EXISTS booking CASCADE;
DROP TABLE IF EXISTS showtime CASCADE;
DROP TABLE IF EXISTS movie CASCADE;
DROP TABLE IF EXISTS cinema_branch CASCADE;
DROP TABLE IF EXISTS customer CASCADE;

CREATE TABLE customer (
    customer_id   SERIAL PRIMARY KEY,
    full_name     VARCHAR(100) NOT NULL,
    email         VARCHAR(100),
    city          VARCHAR(50),
    province      VARCHAR(50),
    segment       VARCHAR(20)
);

CREATE TABLE cinema_branch (
    branch_id     SERIAL PRIMARY KEY,
    branch_name   VARCHAR(100) NOT NULL,
    province      VARCHAR(50)
);

CREATE TABLE movie (
    movie_id      SERIAL PRIMARY KEY,
    title         VARCHAR(150) NOT NULL,
    genre         VARCHAR(50),
    duration_min  INT
);

CREATE TABLE showtime (
    showtime_id     SERIAL PRIMARY KEY,
    movie_id        INT REFERENCES movie(movie_id),
    branch_id       INT REFERENCES cinema_branch(branch_id),
    show_datetime   TIMESTAMP NOT NULL,
    hall_no         INT
);

CREATE TABLE booking (
    booking_id       SERIAL PRIMARY KEY,
    customer_id      INT REFERENCES customer(customer_id),
    showtime_id      INT REFERENCES showtime(showtime_id),
    booking_datetime TIMESTAMP NOT NULL,
    payment_method   VARCHAR(20)
);

CREATE TABLE ticket (
    ticket_id     SERIAL PRIMARY KEY,
    booking_id    INT REFERENCES booking(booking_id),
    seat_no       VARCHAR(10),
    ticket_type   VARCHAR(20),
    price         NUMERIC(10,2)
);

-- ============================================================
-- Seed data
-- ============================================================
INSERT INTO customer (full_name, email, city, province, segment) VALUES
('Somchai Jaidee', 'somchai@example.com', 'Bangkok', 'Bangkok', 'regular'),
('Malee Suksan', 'malee@example.com', 'Chiang Mai', 'Chiang Mai', 'vip'),
('Anan Boonmee', 'anan@example.com', 'Khon Kaen', 'Khon Kaen', 'regular'),
('Suda Wong', 'suda@example.com', 'Bangkok', 'Bangkok', 'vip'),
('Prasert Chai', 'prasert@example.com', 'Hat Yai', 'Songkhla', 'regular'),
('Nok Aree', 'nok@example.com', 'Bangkok', 'Bangkok', 'regular'),
('Wichai Som', 'wichai@example.com', 'Chiang Mai', 'Chiang Mai', 'regular'),
('Pim Chanthorn', 'pim@example.com', 'Khon Kaen', 'Khon Kaen', 'vip'),
('Kittipong Rak', 'kitti@example.com', 'Bangkok', 'Bangkok', 'regular'),
('Ratana Mee', 'ratana@example.com', 'Hat Yai', 'Songkhla', 'regular');

INSERT INTO cinema_branch (branch_name, province) VALUES
('CineStar Siam', 'Bangkok'),
('CineStar Chiang Mai', 'Chiang Mai'),
('CineStar Khon Kaen', 'Khon Kaen'),
('CineStar Hat Yai', 'Songkhla'),
('CineStar Central Bangkok', 'Bangkok');

INSERT INTO movie (title, genre, duration_min) VALUES
('Galaxy Warriors', 'Sci-Fi', 128),
('The Last Recipe', 'Drama', 105),
('Laugh Out Loud', 'Comedy', 96),
('Shadow Hunter', 'Action', 118),
('Whispering Forest', 'Horror', 99),
('Love in Bangkok', 'Romance', 110),
('The Great Robbery', 'Action', 132),
('Ocean''s Melody', 'Musical', 102);

-- 30 showtimes across Jan-Mar (movie_id 1-8, branch_id 1-5)
INSERT INTO showtime (movie_id, branch_id, show_datetime, hall_no)
SELECT
  (1 + (n % 8))                                    AS movie_id,
  (1 + (n % 5))                                    AS branch_id,
  TIMESTAMP '2026-01-05 13:00:00' + (n || ' days')::interval + ((n % 4) || ' hours')::interval AS show_datetime,
  (1 + (n % 3))                                    AS hall_no
FROM generate_series(0, 59) AS n;

-- ~70 bookings across the showtimes
INSERT INTO booking (customer_id, showtime_id, booking_datetime, payment_method)
SELECT
  (1 + (n % 10))                                             AS customer_id,
  (1 + (n % 60))                                              AS showtime_id,
  (SELECT show_datetime FROM showtime WHERE showtime_id = (1 + (n % 60))) - ((1 + n % 5) || ' hours')::interval AS booking_datetime,
  (ARRAY['credit_card','promptpay','cash'])[1 + (n % 3)]     AS payment_method
FROM generate_series(0, 119) AS n;

-- 1-3 tickets per booking, biased by branch popularity (Bangkok branches busier)
INSERT INTO ticket (booking_id, seat_no, ticket_type, price)
SELECT
  b.booking_id,
  chr(65 + (t % 8)) || (1 + (t % 12))                         AS seat_no,
  (ARRAY['standard','vip','student'])[1 + (t % 3)]            AS ticket_type,
  (CASE (t % 3) WHEN 0 THEN 180.00 WHEN 1 THEN 280.00 ELSE 140.00 END) AS price
FROM booking b
JOIN showtime s ON b.showtime_id = s.showtime_id
CROSS JOIN generate_series(
  0,
  1 + (b.booking_id % 3) + (CASE s.branch_id WHEN 1 THEN 3 WHEN 5 THEN 2 WHEN 2 THEN 1 ELSE 0 END)
) AS t;

"""
run(SEED_SQL, fetch=False)
print("โหลด seed data สำเร็จ")

โหลด seed data สำเร็จ

ตรวจสอบว่าโหลดข้อมูลครบ — นับจำนวนแถวในแต่ละตาราง

In [ ]:
for t in ["customer", "cinema_branch", "movie", "showtime", "booking", "ticket"]:
    print(t, "->", run(f"SELECT COUNT(*) AS n FROM {t};").iloc[0]["n"])

customer -> 10
cinema_branch -> 5
movie -> 8
showtime -> 60
booking -> 120
ticket -> 504

### Topic 1: Cloud Data Warehouse (OLTP vs OLAP)

ตาราง OLTP (customer, booking, showtime, ticket, ...) ถูกออกแบบให้ insert/update ได้รวดเร็ว แต่ไม่ได้เหมาะกับการ query เชิงวิเคราะห์

**แบบฝึกหัด:** เขียน SQL หา ยอดขายตั๋วรวม (บาท) แยกตามสาขา และเดือน โดย query ตรงจากตาราง OLTP (ต้อง JOIN ticket -> booking -> showtime -> cinema_branch) แล้วตอบคำถามว่า query นี้ อ่านและดูแลรักษายากกว่า query บน Star Schema (ที่จะสร้างในหัวข้อถัดไป) อย่างไร

In [4]:
result = run("""
SELECT
    cb.branch_name,
    EXTRACT(MONTH FROM s.show_datetime) AS month,
    SUM(t.price) AS revenue
FROM ticket t
JOIN booking b ON t.booking_id = b.booking_id
JOIN showtime s ON b.showtime_id = s.showtime_id
JOIN cinema_branch cb ON s.branch_id = cb.branch_id
GROUP BY cb.branch_name, EXTRACT(MONTH FROM s.show_datetime)
ORDER BY cb.branch_name, month;
""")
result

                 branch_name month   revenue
0   CineStar Central Bangkok     1  10600.00
1   CineStar Central Bangkok     2  12160.00
2   CineStar Central Bangkok     3   1560.00
3        CineStar Chiang Mai     1   9760.00
4        CineStar Chiang Mai     2   8560.00
5        CineStar Chiang Mai     3   1200.00
6           CineStar Hat Yai     1   5800.00
7           CineStar Hat Yai     2   7360.00
8           CineStar Hat Yai     3   1560.00
9         CineStar Khon Kaen     1   6160.00
10        CineStar Khon Kaen     2   7360.00
11        CineStar Khon Kaen     3   1200.00
12             CineStar Siam     1  14560.00
13             CineStar Siam     2  11800.00
14             CineStar Siam     3   2760.00

In [ ]:
#ตัวอย่างผลลัพธ์

                 branch_name month   revenue
0   CineStar Central Bangkok     1  10600.00
1   CineStar Central Bangkok     2  12160.00
2   CineStar Central Bangkok     3   1560.00
3        CineStar Chiang Mai     1   9760.00
4        CineStar Chiang Mai     2   8560.00
5        CineStar Chiang Mai     3   1200.00
6           CineStar Hat Yai     1   5800.00
7           CineStar Hat Yai     2   7360.00
8           CineStar Hat Yai     3   1560.00
9         CineStar Khon Kaen     1   6160.00
10        CineStar Khon Kaen     2   7360.00
11        CineStar Khon Kaen     3   1200.00
12             CineStar Siam     1  14560.00
13             CineStar Siam     2  11800.00
14             CineStar Siam     3   2760.00

### Topic 2: Dimensional Modeling (Business Process, Grain, Dimensions, Measures)

ก่อนที่จะเริ่มออกแบบ Star Schema เราจะต้องตอบคำถามทางธุรกิจก่อน เช่น

ผู้บริหารเครือ CineStar ถามว่า "ภาพยนตร์เรื่องไหนทำรายได้ดีที่สุดในแต่ละสาขา โดยให้แยกตามเดือน?"

เมื่อ Business Process คือ Ticket Sales (การขายตั๋วภาพยนตร์)

ให้ระบุ (2) Grain (3) Dimensions ที่ต้องมี (4) Measures ที่ต้องมี เขียนคำตอบในเซลล์ markdown ถัดไป

**คำตอบของฉัน:**

- Business Process: Ticket Sales (การขายตั๋วภาพยนตร์)
- Grain: ...
- Dimensions: ...
- Measures: ...

### Topic 3: Fact Tables

Grain ที่ตกลงกันไว้คือ 1 row = 1 ticket แปลว่า fact table ต้องมี 1 แถวต่อตั๋ว 1 ใบ

**แบบฝึกหัด:** สร้างตาราง fact_ticket_sales_draft ที่มี grain = 1 ticket โดยยังใช้ natural key ตรงๆ จากตาราง OLTP ไปก่อน แล้ว INSERT ข้อมูลเข้าไป ด้วยการ JOIN ticket -> booking -> showtime

In [5]:
run("""
DROP TABLE IF EXISTS fact_ticket_sales_draft;
CREATE TABLE fact_ticket_sales_draft (
    ticket_id    INT PRIMARY KEY,
    customer_id  INT,
    movie_id     INT,
    branch_id    INT,
    show_date    DATE,
    ticket_type  VARCHAR(20),
    price        NUMERIC(10,2)
);
""", fetch=False)

run("""
INSERT INTO fact_ticket_sales_draft
SELECT
    t.ticket_id,
    b.customer_id,
    s.movie_id,
    s.branch_id,
    s.show_datetime::date AS show_date,
    t.ticket_type,
    t.price
FROM ticket t
JOIN booking b ON t.booking_id = b.booking_id
JOIN showtime s ON b.showtime_id = s.showtime_id;
""", fetch=False)

run("SELECT COUNT(*) FROM fact_ticket_sales_draft;")

   count
0    504

In [ ]:
#ตัวอย่างผลลัพธ์

   count
0    504

### Topic 4: Dimension Tables (Surrogate Key + SCD Type 2)

Dimension table ควรมี surrogate key ของตัวเอง (ไม่ใช่ natural key จาก OLTP โดยตรง) เพื่อรองรับการเก็บ history แบบ SCD Type 2

**แบบฝึกหัด:** สร้าง dim_customer ที่มี surrogate key (customer_key) และ column effective_date, end_date, is_current แล้วจำลองสถานการณ์ที่ลูกค้า Malee Suksan (customer_id = 2) ย้ายจาก Chiang Mai ไป Bangkok - ให้ทำ SCD Type 2 (ปิด row เดิมด้วย end_date และเพิ่ม row ใหม่)

In [6]:
run("""
DROP TABLE IF EXISTS dim_customer CASCADE;
CREATE TABLE dim_customer (
    customer_key   SERIAL PRIMARY KEY,
    customer_id    INT,
    full_name      VARCHAR(100),
    city           VARCHAR(50),
    province       VARCHAR(50),
    segment        VARCHAR(20),
    effective_date DATE DEFAULT '2026-01-01',
    end_date       DATE,
    is_current     BOOLEAN DEFAULT TRUE
);
INSERT INTO dim_customer (customer_id, full_name, city, province, segment)
SELECT customer_id, full_name, city, province, segment FROM customer;
""", fetch=False)

# TODO: SCD Type 2 สำหรับ customer_id = 2
# 1: UPDATE row เดิมให้ end_date = '2026-02-28' และ is_current = FALSE
run("""
UPDATE dim_customer
SET end_date = '2026-02-28', is_current = FALSE
WHERE customer_id = 2 AND is_current = TRUE;
""", fetch=False)

# 2: INSERT row ใหม่ city='Bangkok', province='Bangkok', effective_date='2026-03-01', is_current=TRUE
run("""
INSERT INTO dim_customer (customer_id, full_name, city, province, segment, effective_date, is_current)
SELECT
    c.customer_id,
    c.full_name,
    'Bangkok' AS city,
    'Bangkok' AS province,
    c.segment,
    DATE '2026-03-01' AS effective_date,
    TRUE AS is_current
FROM customer c
WHERE c.customer_id = 2;
""", fetch=False)

run("SELECT * FROM dim_customer WHERE customer_id = 2 ORDER BY customer_key;")

,customer_key,customer_id,full_name,city,province,segment,effective_date,end_date,is_current
0,2,2,Malee Suksan,Chiang Mai,Chiang Mai,vip,2026-01-01,2026-02-28,False
1,11,2,Malee Suksan,Bangkok,Bangkok,vip,2026-03-01,None,True

In [ ]:
#ตัวอย่างผลลัพธ์

,customer_key,customer_id,full_name,city,province,segment,effective_date,end_date,is_current
0,2,2,Malee Suksan,Chiang Mai,Chiang Mai,vip,2026-01-01,2026-02-28,False
1,11,2,Malee Suksan,Bangkok,Bangkok,vip,2026-03-01,None,True

### Topic 5: Star vs Snowflake Schema

ตอนนี้มี dim_customer แล้ว เหลือสร้าง dim_movie, dim_branch, dim_date แล้วรวมเป็น fact_ticket_sales ที่ใช้ surrogate key ทั้งหมด (Star Schema สมบูรณ์)

**แบบฝึกหัด:** สร้าง dim_movie, dim_branch, dim_date (surrogate key ทั้งหมด) และ fact_ticket_sales แบบเต็มรูปแบบ (ใช้ surrogate key จากทุก dimension) แล้วเขียน Star-Schema query หา 3 อันดับภาพยนตร์ที่ทำรายได้สูงสุด

In [7]:
run("""
DROP TABLE IF EXISTS dim_movie CASCADE;
CREATE TABLE dim_movie (movie_key SERIAL PRIMARY KEY, movie_id INT, title VARCHAR(150), genre VARCHAR(50), duration_min INT);
INSERT INTO dim_movie (movie_id, title, genre, duration_min) SELECT movie_id, title, genre, duration_min FROM movie;

DROP TABLE IF EXISTS dim_branch CASCADE;
CREATE TABLE dim_branch (branch_key SERIAL PRIMARY KEY, branch_id INT, branch_name VARCHAR(100), province VARCHAR(50));
INSERT INTO dim_branch (branch_id, branch_name, province) SELECT branch_id, branch_name, province FROM cinema_branch;

DROP TABLE IF EXISTS dim_date CASCADE;
CREATE TABLE dim_date AS
SELECT DISTINCT s.show_datetime::date AS date_key,
    EXTRACT(YEAR FROM s.show_datetime)::INT AS year,
    EXTRACT(MONTH FROM s.show_datetime)::INT AS month,
    TO_CHAR(s.show_datetime, 'Month') AS month_name,
    EXTRACT(DAY FROM s.show_datetime)::INT AS day
FROM showtime s;
ALTER TABLE dim_date ADD PRIMARY KEY (date_key);
""", fetch=False)

run("""
DROP TABLE IF EXISTS fact_ticket_sales CASCADE;
CREATE TABLE fact_ticket_sales (
    ticket_id     INT PRIMARY KEY,
    date_key      DATE REFERENCES dim_date(date_key),
    customer_key  INT REFERENCES dim_customer(customer_key),
    movie_key     INT REFERENCES dim_movie(movie_key),
    branch_key    INT REFERENCES dim_branch(branch_key),
    ticket_type   VARCHAR(20),
    price         NUMERIC(10,2)
);
INSERT INTO fact_ticket_sales (ticket_id, date_key, customer_key, movie_key, branch_key, ticket_type, price)
SELECT t.ticket_id, s.show_datetime::date, dc.customer_key, dm.movie_key, db.branch_key, t.ticket_type, t.price
FROM ticket t
JOIN booking b   ON t.booking_id = b.booking_id
JOIN showtime s  ON b.showtime_id = s.showtime_id
JOIN dim_customer dc ON dc.customer_id = b.customer_id AND dc.is_current
JOIN dim_movie dm    ON dm.movie_id = s.movie_id
JOIN dim_branch db   ON db.branch_id = s.branch_id;
""", fetch=False)

# TODO: Star-Schema query หา Top 3 ภาพยนตร์ตามรายได้
run("""
SELECT dm.title, SUM(f.price) AS revenue
FROM fact_ticket_sales f
JOIN dim_movie dm ON f.movie_key = dm.movie_key
GROUP BY dm.title
ORDER BY revenue DESC
LIMIT 3;
""")

             title   revenue
0  The Last Recipe  13920.00
1  Galaxy Warriors  13640.00
2   Laugh Out Loud  13360.00

In [ ]:
#ตัวอย่างผลลัพธ์

             title   revenue
0  The Last Recipe  13920.00
1  Galaxy Warriors  13640.00
2   Laugh Out Loud  13360.00

### Topic 6: dbt & ELT - ตั้งค่าโปรเจกต์

ต่อไปเราจะสร้าง fact/dimension แบบเดียวกับที่ทำใน Topic 3-5 แต่ทำผ่าน dbt แทน SQL ตรงๆ เพื่อให้ได้ dependency graph, testing, และ documentation ติดมาด้วย

สร้าง dbt project ชื่อ cinema_dbt ตั้งค่า profiles.yml ให้ชี้ไปที่ Neon Postgres ของคุณ (ใช้ตัวแปร PGHOST/PGUSER/... ที่ตั้งไว้ใน Setup) และสร้าง sources.yml ที่ระบุตาราง OLTP ทั้ง 6 ตาราง

In [11]:
import os
if os.path.exists('/content'):
    os.chdir('/content')

!dbt init cinema_dbt --skip-profile-setup
os.chdir('cinema_dbt')
os.environ['DBT_PROFILES_DIR'] = os.getcwd()

# dbt init สร้างโฟลเดอร์ models/example/ มาเป็นตัวอย่าง (มี test ที่ตั้งใจให้ fail เพื่อสาธิต) ลบทิ้งก่อน
import shutil
shutil.rmtree('models/example', ignore_errors=True)

profiles_yml = f"""
cinema_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: {PGHOST}
      user: {PGUSER}
      password: {PGPASSWORD}
      port: {PGPORT}
      dbname: {PGDATABASE}
      schema: public
      threads: 4
      sslmode: require
"""
with open('profiles.yml', 'w') as f:
    f.write(profiles_yml)

os.makedirs('models/staging', exist_ok=True)
sources_yml = """
version: 2

sources:
  - name: cinema_oltp
    schema: public
    tables:
      - name: customer
      - name: cinema_branch
      - name: movie
      - name: showtime
      - name: booking
      - name: ticket
"""
with open('models/staging/sources.yml', 'w') as f:
    f.write(sources_yml)

!dbt debug

07:26:10  Running with dbt=1.12.5
07:26:10  Creating dbt configuration folder at /root/.dbt
07:26:10  Your new dbt project "cinema_dbt" was created!
Initialized new project in /content/cinema_dbt/cinema_dbt

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

07:26:15  Running with dbt=1.12.5
07:26:15  dbt version: 1.12.5
07:26:15  python version: 3.13.15
07:26:15  python path: /usr/bin/python3
07:26:15  os info: Linux-6.6.122+-x86_64-with-glibc2.39
07:26:15  Using profiles dir at /content/cinema_dbt
07:26:15  Using profiles.yml file at /content/cinema_dbt/profiles.yml
07:26:15  Using dbt_project.yml file at /content/cinema_dbt/dbt_project.yml
07:26:15  adapter type: postgres
07:26:15  adapter version: 1.11.0
07:26:16  Configuration:
07:26:16    profiles.yml file [OK found and valid]
07:26:16    dbt_project.yml file [OK found and valid]
07:26:16  Required dependencies:
07:26:16   - git [OK found]

07:26:16  Connection:
07:26:16    host: ep-calm-violet-b3eqp600-pooler.c-4.ap-southeast-1.aws.neon.tech
07:26:16    port: 5432
07:26:16    user: neondb_owner
07:26:16    database: neondb
07:26:16    schema: public
07:26:16    connect_timeout: 10
07:26:16    role: None
07:26:16    search_path: None
07:26:16    keepalives_idle: 0
07:26:16    sslmode: require
07:26:16    sslcert: None
07:26:16    sslkey: None
07:26:16    sslrootcert: None
07:26:16    application_name: dbt
07:26:16    autocommit: False
07:26:16    retries: 1
07:26:16  Registered adapter: postgres=1.11.0
07:26:18    Connection test: [OK connection ok]

07:26:18  All checks passed!

### Topic 7: dbt Models & Materializations

สร้าง staging models ด้วย source() และ intermediate model ด้วย ref()

เขียน stg_bookings.sql และ stg_tickets.sql (ใช้ source()) แล้วเขียน int_ticket_bookings.sql ที่ JOIN ทั้งสองเข้ากับ stg_showtimes (ใช้ ref()) ไฟล์ stg_customers.sql, stg_movies.sql, stg_branches.sql, stg_showtimes.sql ที่มี

In [12]:
from pathlib import Path
import os

Path('models/staging/stg_customers.sql').write_text(
    "select customer_id, full_name, email, city, province, segment "
    "from {{ source('cinema_oltp', 'customer') }}"
)
Path('models/staging/stg_branches.sql').write_text(
    "select branch_id, branch_name, province from {{ source('cinema_oltp', 'cinema_branch') }}"
)
Path('models/staging/stg_movies.sql').write_text(
    "select movie_id, title, genre, duration_min from {{ source('cinema_oltp', 'movie') }}"
)
Path('models/staging/stg_showtimes.sql').write_text(
    "select showtime_id, movie_id, branch_id, show_datetime, show_datetime::date as show_date, hall_no "
    "from {{ source('cinema_oltp', 'showtime') }}"
)

Path('models/staging/stg_bookings.sql').write_text(
    "select booking_id, customer_id, showtime_id, booking_datetime, payment_method "
    "from {{ source('cinema_oltp', 'booking') }}"
)

Path('models/staging/stg_tickets.sql').write_text(
    "select ticket_id, booking_id, seat_no, ticket_type, price "
    "from {{ source('cinema_oltp', 'ticket') }}"
)

os.makedirs('models/intermediate', exist_ok=True)
Path('models/intermediate/int_ticket_bookings.sql').write_text("""
select
    t.ticket_id, t.ticket_type, t.price,
    b.booking_id, b.customer_id, b.payment_method,
    s.showtime_id, s.movie_id, s.branch_id, s.show_date
from {{ ref('stg_tickets') }} t
join {{ ref('stg_bookings') }} b on t.booking_id = b.booking_id
join {{ ref('stg_showtimes') }} s on b.showtime_id = s.showtime_id
""")

!dbt run

07:26:51  Running with dbt=1.12.5
07:26:52  Registered adapter: postgres=1.11.0
07:26:52  Unable to do partial parsing because saved manifest not found. Starting full parse.
07:26:54  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.cinema_dbt.example
07:26:54  Found 7 models, 6 sources, 477 macros
07:26:54
07:26:54  Concurrency: 4 threads (target='dev')
07:26:54
07:27:01  4 of 7 START sql view model public.stg_movies .................................. [RUN]
07:27:01  3 of 7 START sql view model public.stg_customers ............................... [RUN]
07:27:01  1 of 7 START sql view model public.stg_bookings ................................ [RUN]
07:27:01  2 of 7 START sql view model public.stg_branches ................................ [RUN]
07:27:04  2 of 7 OK created sql view model public.stg_branches ........................... [CREATE VIEW in 3.03s]
07:27:04  1 of 7 OK created sql view model public.stg_bookings ........................... [CREATE VIEW in 3.04s]
07:27:04  5 of 7 START sql view model public.stg_showtimes ............................... [RUN]
07:27:04  6 of 7 START sql view model public.stg_tickets ................................. [RUN]
07:27:04  4 of 7 OK created sql view model public.stg_movies ............................. [CREATE VIEW in 3.08s]
07:27:04  3 of 7 OK created sql view model public.stg_customers .......................... [CREATE VIEW in 3.09s]
07:27:07  6 of 7 OK created sql view model public.stg_tickets ............................ [CREATE VIEW in 2.83s]
07:27:07  5 of 7 OK created sql view model public.stg_showtimes .......................... [CREATE VIEW in 2.87s]
07:27:07  7 of 7 START sql view model public.int_ticket_bookings ......................... [RUN]
07:27:10  7 of 7 OK created sql view model public.int_ticket_bookings .................... [CREATE VIEW in 2.58s]
07:27:11
07:27:11  Finished running 7 view models in 0 hours 0 minutes and 17.06 seconds (17.06s).
07:27:11
07:27:11  Completed successfully
07:27:11
07:27:11  Done. PASS=7 WARN=0 ERROR=0 SKIP=0 NO-OP=0 REUSED=0 TOTAL=7

### Topic 8: dbt Testing & Documentation

dbt tests คือฟีเจอร์ในตัวของ dbt ที่ให้เขียน "กฎ" ตรวจสอบคุณภาพข้อมูล (data quality) ผ่าน YAML แทนที่จะต้องเขียน SQL ตรวจเองทุกครั้ง — dbt จะ compile กฎเหล่านั้นเป็น SQL query แล้วรันให้อัตโนมัติ

ให้เพิ่ม dbt tests ให้กับ stg_bookings และ stg_tickets

เขียน schema.yml ที่มี not_null+unique บน primary key ของทั้งสอง model และ accepted_values บน payment_method (ต้องเป็นหนึ่งใน credit_card, promptpay, cash) แล้วรัน dbt test และ dbt docs generate

In [13]:
from pathlib import Path

staging_schema_yml = """
version: 2

models:
  - name: stg_bookings
    columns:
      - name: booking_id
        tests: [unique, not_null]
      - name: payment_method
        tests:
          - accepted_values:
              values: ['credit_card', 'promptpay', 'cash']

  - name: stg_tickets
    columns:
      - name: ticket_id
        tests: [unique, not_null]
"""
Path('models/staging/staging_schema.yml').write_text(staging_schema_yml)

!dbt test
!dbt docs generate

07:27:25  Running with dbt=1.12.5
07:27:26  Registered adapter: postgres=1.11.0
07:27:27  [WARNING][MissingArgumentsPropertyInGenericTestDeprecation]: Deprecated
functionality
Found top-level arguments to test `accepted_values` defined on 'stg_bookings' in
package 'cinema_dbt' (models/staging/staging_schema.yml). Arguments to generic
tests should be nested under the `arguments` property.
07:27:27  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.cinema_dbt.example
07:27:27  Found 7 models, 5 data tests, 6 sources, 477 macros
07:27:27
07:27:27  Concurrency: 4 threads (target='dev')
07:27:27
07:27:32  1 of 5 START test accepted_values_stg_bookings_payment_method__credit_card__promptpay__cash  [RUN]
07:27:32  2 of 5 START test not_null_stg_bookings_booking_id ............................. [RUN]
07:27:32  3 of 5 START test not_null_stg_tickets_ticket_id ............................... [RUN]
07:27:32  4 of 5 START test unique_stg_bookings_booking_id ............................... [RUN]
07:27:34  2 of 5 PASS not_null_stg_bookings_booking_id ................................... [PASS in 2.29s]
07:27:34  5 of 5 START test unique_stg_tickets_ticket_id ................................. [RUN]
07:27:34  1 of 5 PASS accepted_values_stg_bookings_payment_method__credit_card__promptpay__cash  [PASS in 2.31s]
07:27:34  4 of 5 PASS unique_stg_bookings_booking_id ..................................... [PASS in 2.33s]
07:27:34  3 of 5 PASS not_null_stg_tickets_ticket_id ..................................... [PASS in 2.35s]
07:27:36  5 of 5 PASS unique_stg_tickets_ticket_id ....................................... [PASS in 2.05s]
07:27:38
07:27:38  Finished running 5 data tests in 0 hours 0 minutes and 10.94 seconds (10.94s).
07:27:38
07:27:38  Completed successfully
07:27:38
07:27:38  Done. PASS=5 WARN=0 ERROR=0 SKIP=0 NO-OP=0 REUSED=0 TOTAL=5
07:27:38  [WARNING][DeprecationsSummary]: Deprecated functionality
Summary of encountered deprecations:
- MissingArgumentsPropertyInGenericTestDeprecation: 1 occurrence
To see all deprecation instances instead of just the first occurrence of each,
run command again with the `--show-all-deprecations` flag. You may also need to
run with `--no-partial-parse` as some deprecations are only encountered during
parsing.
07:27:44  Running with dbt=1.12.5
07:27:44  Registered adapter: postgres=1.11.0
07:27:45  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.cinema_dbt.example
07:27:45  Found 7 models, 5 data tests, 6 sources, 477 macros
07:27:45
07:27:45  Concurrency: 4 threads (target='dev')
07:27:45
07:27:50  Building catalog
07:27:52  Catalog written to /content/cinema_dbt/target/catalog.json

## ตัวอย่างเพิ่มเติม - สร้าง Analytics Data Warehouse ให้ครบวงจร

ตอนนี้มี staging + intermediate layer พร้อมแล้ว งานสุดท้ายคือสร้าง mart layer ให้ครบ แล้วตอบคำถามทางธุรกิจของผู้บริหาร CineStar ด้วย SQL บน mart ที่สร้างเสร็จ

**โจทย์:** สร้าง dbt models ต่อไปนี้ในโฟลเดอร์ models/marts/:

1. dim_customer.sql, dim_movie.sql, dim_branch.sql - materialized เป็น table ใช้ row_number() สร้าง surrogate key
2. dim_date.sql - materialized เป็น table, distinct วันที่จาก stg_showtimes
3. fct_ticket_sales.sql - materialized เป็น table, grain = 1 ticket, JOIN int_ticket_bookings กับ dimension ทั้งสี่
4. mart_monthly_sales.sql - materialized เป็น view, สรุปยอดขายตามปี/เดือน/ภาพยนตร์/สาขา
5. เพิ่ม schema.yml ใน models/marts/ ที่มี unique+not_null บนทุก surrogate key และ relationships เชื่อม fct_ticket_sales กับ dimension ทั้งสาม

จากนั้นรัน dbt run และ dbt test ให้ผ่านทั้งหมด:

- Q1: เดือนไหนขายตั๋วได้รายได้รวมสูงสุด?
- Q2: ภาพยนตร์เรื่องไหนทำรายได้สูงสุด 3 อันดับแรก (รวมทุกสาขา)?
- Q3: สาขาไหนขายตั๋วได้มากที่สุด (จำนวนใบ)?

In [14]:
from pathlib import Path
import os
os.makedirs('models/marts', exist_ok=True)

Path('models/marts/dim_customer.sql').write_text("""
{{ config(materialized='table') }}
select
    row_number() over (order by customer_id) as customer_key,
    customer_id, full_name, city, province, segment
from {{ ref('stg_customers') }}
""")

Path('models/marts/dim_movie.sql').write_text("""
{{ config(materialized='table') }}
select
    row_number() over (order by movie_id) as movie_key,
    movie_id, title, genre, duration_min
from {{ ref('stg_movies') }}
""")

Path('models/marts/dim_branch.sql').write_text("""
{{ config(materialized='table') }}
select
    row_number() over (order by branch_id) as branch_key,
    branch_id, branch_name, province
from {{ ref('stg_branches') }}
""")

Path('models/marts/dim_date.sql').write_text("""
{{ config(materialized='table') }}
select distinct
    show_date as date_key,
    extract(year from show_date)::int as year,
    extract(month from show_date)::int as month,
    to_char(show_date, 'Month') as month_name,
    extract(day from show_date)::int as day
from {{ ref('stg_showtimes') }}
""")

Path('models/marts/fct_ticket_sales.sql').write_text("""
{{ config(materialized='table') }}
select
    ib.ticket_id,
    ib.show_date as date_key,
    dc.customer_key, dm.movie_key, db.branch_key,
    ib.ticket_type, ib.price
from {{ ref('int_ticket_bookings') }} ib
join {{ ref('dim_customer') }} dc on dc.customer_id = ib.customer_id
join {{ ref('dim_movie') }} dm on dm.movie_id = ib.movie_id
join {{ ref('dim_branch') }} db on db.branch_id = ib.branch_id
""")

Path('models/marts/mart_monthly_sales.sql').write_text("""
{{ config(materialized='view') }}
select
    d.year, d.month, d.month_name,
    dm.title as movie_title, db.branch_name,
    count(f.ticket_id) as tickets_sold,
    sum(f.price) as revenue
from {{ ref('fct_ticket_sales') }} f
join {{ ref('dim_date') }} d on f.date_key = d.date_key
join {{ ref('dim_movie') }} dm on f.movie_key = dm.movie_key
join {{ ref('dim_branch') }} db on f.branch_key = db.branch_key
group by d.year, d.month, d.month_name, dm.title, db.branch_name
""")

marts_schema_yml = """
version: 2

models:
  - name: dim_customer
    columns:
      - name: customer_key
        tests: [unique, not_null]
  - name: dim_movie
    columns:
      - name: movie_key
        tests: [unique, not_null]
  - name: dim_branch
    columns:
      - name: branch_key
        tests: [unique, not_null]
  - name: fct_ticket_sales
    columns:
      - name: ticket_id
        tests: [unique, not_null]
      - name: customer_key
        tests:
          - relationships:
              to: ref('dim_customer')
              field: customer_key
      - name: movie_key
        tests:
          - relationships:
              to: ref('dim_movie')
              field: movie_key
      - name: branch_key
        tests:
          - relationships:
              to: ref('dim_branch')
              field: branch_key
"""
Path('models/marts/schema.yml').write_text(marts_schema_yml)

!dbt run
!dbt test
!dbt docs generate

07:28:07  Running with dbt=1.12.5
07:28:07  Registered adapter: postgres=1.11.0
07:28:10  [WARNING][MissingArgumentsPropertyInGenericTestDeprecation]: Deprecated
functionality
Found top-level arguments to test `relationships` defined on 'fct_ticket_sales'
in package 'cinema_dbt' (models/marts/schema.yml). Arguments to generic tests
should be nested under the `arguments` property.
07:28:10  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.cinema_dbt.example
07:28:10  Found 13 models, 16 data tests, 6 sources, 477 macros
07:28:10
07:28:10  Concurrency: 4 threads (target='dev')
07:28:10
07:28:17  1 of 13 START sql view model public.stg_bookings ............................... [RUN]
07:28:17  3 of 13 START sql view model public.stg_customers .............................. [RUN]
07:28:17  4 of 13 START sql view model public.stg_movies ................................. [RUN]
07:28:17  2 of 13 START sql view model public.stg_branches ............................... [RUN]
07:28:20  1 of 13 OK created sql view model public.stg_bookings .......................... [CREATE VIEW in 2.95s]
07:28:20  2 of 13 OK created sql view model public.stg_branches .......................... [CREATE VIEW in 2.93s]
07:28:20  5 of 13 START sql view model public.stg_showtimes .............................. [RUN]
07:28:20  6 of 13 START sql view model public.stg_tickets ................................ [RUN]
07:28:20  3 of 13 OK created sql view model public.stg_customers ......................... [CREATE VIEW in 2.98s]
07:28:20  7 of 13 START sql table model public.dim_branch ................................ [RUN]
07:28:20  4 of 13 OK created sql view model public.stg_movies ............................ [CREATE VIEW in 3.07s]
07:28:20  8 of 13 START sql table model public.dim_customer .............................. [RUN]
07:28:23  5 of 13 OK created sql view model public.stg_showtimes ......................... [CREATE VIEW in 2.75s]
07:28:23  9 of 13 START sql table model public.dim_movie ................................. [RUN]
07:28:23  7 of 13 OK created sql table model public.dim_branch ........................... [SELECT 5 in 2.82s]
07:28:23  10 of 13 START sql table model public.dim_date ................................. [RUN]
07:28:23  6 of 13 OK created sql view model public.stg_tickets ........................... [CREATE VIEW in 2.92s]
07:28:23  11 of 13 START sql view model public.int_ticket_bookings ....................... [RUN]
07:28:23  8 of 13 OK created sql table model public.dim_customer ......................... [SELECT 10 in 2.90s]
07:28:26  11 of 13 OK created sql view model public.int_ticket_bookings .................. [CREATE VIEW in 2.64s]
07:28:26  9 of 13 OK created sql table model public.dim_movie ............................ [SELECT 8 in 2.83s]
07:28:26  12 of 13 START sql table model public.fct_ticket_sales ......................... [RUN]
07:28:26  10 of 13 OK created sql table model public.dim_date ............................ [SELECT 60 in 2.87s]
07:28:28  12 of 13 OK created sql table model public.fct_ticket_sales .................... [SELECT 504 in 2.57s]
07:28:28  13 of 13 START sql view model public.mart_monthly_sales ........................ [RUN]
07:28:31  13 of 13 OK created sql view model public.mart_monthly_sales ................... [CREATE VIEW in 2.69s]
07:28:33
07:28:33  Finished running 5 table models, 8 view models in 0 hours 0 minutes and 22.43 seconds (22.43s).
07:28:33
07:28:33  Completed successfully
07:28:33
07:28:33  Done. PASS=13 WARN=0 ERROR=0 SKIP=0 NO-OP=0 REUSED=0 TOTAL=13
07:28:33  [WARNING][DeprecationsSummary]: Deprecated functionality
Summary of encountered deprecations:
- MissingArgumentsPropertyInGenericTestDeprecation: 3 occurrences
To see all deprecation instances instead of just the first occurrence of each,
run command again with the `--show-all-deprecations` flag. You may also need to
run with `--no-partial-parse` as some deprecations are only encountered during
parsing.
07:28:40  Running with dbt=1.12.5
07:28:41  Registered adapter: postgres=1.11.0
07:28:41  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.cinema_dbt.example
07:28:41  Found 13 models, 16 data tests, 6 sources, 477 macros
07:28:41
07:28:41  Concurrency: 4 threads (target='dev')
07:28:41
07:28:46  1 of 16 START test accepted_values_stg_bookings_payment_method__credit_card__promptpay__cash  [RUN]
07:28:46  4 of 16 START test not_null_dim_movie_movie_key ................................ [RUN]
07:28:46  3 of 16 START test not_null_dim_customer_customer_key .......................... [RUN]
07:28:46  2 of 16 START test not_null_dim_branch_branch_key .............................. [RUN]
07:28:48  1 of 16 PASS accepted_values_stg_bookings_payment_method__credit_card__promptpay__cash  [PASS in 2.26s]
07:28:48  5 of 16 START test not_null_fct_ticket_sales_ticket_id ......................... [RUN]
07:28:48  3 of 16 PASS not_null_dim_customer_customer_key ................................ [PASS in 2.25s]
07:28:48  6 of 16 START test not_null_stg_bookings_booking_id ............................ [RUN]
07:28:48  4 of 16 PASS not_null_dim_movie_movie_key ...................................... [PASS in 2.30s]
07:28:48  2 of 16 PASS not_null_dim_branch_branch_key .................................... [PASS in 2.28s]
07:28:48  7 of 16 START test not_null_stg_tickets_ticket_id .............................. [RUN]
07:28:48  8 of 16 START test relationships_fct_ticket_sales_branch_key__branch_key__ref_dim_branch_  [RUN]
07:28:50  5 of 16 PASS not_null_fct_ticket_sales_ticket_id ............................... [PASS in 2.13s]
07:28:50  9 of 16 START test relationships_fct_ticket_sales_customer_key__customer_key__ref_dim_customer_  [RUN]
07:28:50  6 of 16 PASS not_null_stg_bookings_booking_id .................................. [PASS in 2.15s]
07:28:50  10 of 16 START test relationships_fct_ticket_sales_movie_key__movie_key__ref_dim_movie_  [RUN]
07:28:50  8 of 16 PASS relationships_fct_ticket_sales_branch_key__branch_key__ref_dim_branch_  [PASS in 2.12s]
07:28:50  11 of 16 START test unique_dim_branch_branch_key ............................... [RUN]
07:28:50  7 of 16 PASS not_null_stg_tickets_ticket_id .................................... [PASS in 2.16s]
07:28:50  12 of 16 START test unique_dim_customer_customer_key ........................... [RUN]
07:28:52  12 of 16 PASS unique_dim_customer_customer_key ................................. [PASS in 2.04s]
07:28:52  13 of 16 START test unique_dim_movie_movie_key ................................. [RUN]
07:28:52  9 of 16 PASS relationships_fct_ticket_sales_customer_key__customer_key__ref_dim_customer_  [PASS in 2.17s]
07:28:52  14 of 16 START test unique_fct_ticket_sales_ticket_id .......................... [RUN]
07:28:52  11 of 16 PASS unique_dim_branch_branch_key ..................................... [PASS in 2.09s]
07:28:52  15 of 16 START test unique_stg_bookings_booking_id ............................. [RUN]
07:28:53  10 of 16 PASS relationships_fct_ticket_sales_movie_key__movie_key__ref_dim_movie_  [PASS in 2.21s]
07:28:53  16 of 16 START test unique_stg_tickets_ticket_id ............................... [RUN]
07:28:55  13 of 16 PASS unique_dim_movie_movie_key ....................................... [PASS in 2.08s]
07:28:55  14 of 16 PASS unique_fct_ticket_sales_ticket_id ................................ [PASS in 2.06s]
07:28:55  15 of 16 PASS unique_stg_bookings_booking_id ................................... [PASS in 2.12s]
07:28:55  16 of 16 PASS unique_stg_tickets_ticket_id ..................................... [PASS in 2.07s]
07:28:56
07:28:56  Finished running 16 data tests in 0 hours 0 minutes and 15.26 seconds (15.26s).
07:28:57
07:28:57  Completed successfully
07:28:57
07:28:57  Done. PASS=16 WARN=0 ERROR=0 SKIP=0 NO-OP=0 REUSED=0 TOTAL=16
07:29:03  Running with dbt=1.12.5
07:29:04  Registered adapter: postgres=1.11.0
07:29:04  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.cinema_dbt.example
07:29:04  Found 13 models, 16 data tests, 6 sources, 477 macros
07:29:04
07:29:04  Concurrency: 4 threads (target='dev')
07:29:04
07:29:09  Building catalog
07:29:11  Catalog written to /content/cinema_dbt/target/catalog.json

### ให้เขียนโค้ดเพื่อตอบคำถามทางธุรกิจจาก mart_monthly_sales

In [15]:
# Q1: เดือนไหนขายตั๋วได้รายได้รวมสูงสุด?
run("""
SELECT year, month_name, SUM(revenue) AS monthly_revenue
FROM mart_monthly_sales
GROUP BY year, month_name
ORDER BY monthly_revenue DESC
LIMIT 1;
""")

   year month_name monthly_revenue
0  2026  February         47240.00

In [ ]:
# ตัวอย่างผลลัพธ์

   year month_name monthly_revenue
0  2026  February         47240.00

In [16]:
# Q2: ภาพยนตร์เรื่องไหนทำรายได้สูงสุด 3 อันดับแรก (รวมทุกสาขา)?
run("""
SELECT movie_title, SUM(revenue) AS total_revenue
FROM mart_monthly_sales
GROUP BY movie_title
ORDER BY total_revenue DESC
LIMIT 3;
""")

       movie_title total_revenue
0  The Last Recipe      13920.00
1  Galaxy Warriors      13640.00
2   Laugh Out Loud      13360.00

In [ ]:
# ตัวอย่างผลลัพธ์

       movie_title total_revenue
0  The Last Recipe      13920.00
1  Galaxy Warriors      13640.00
2   Laugh Out Loud      13360.00

In [17]:
# Q3: สาขาไหนขายตั๋วได้มากที่สุด (จำนวนใบ)?
run("""
SELECT branch_name, SUM(tickets_sold) AS total_tickets
FROM mart_monthly_sales
GROUP BY branch_name
ORDER BY total_tickets DESC
LIMIT 1;
""")

     branch_name total_tickets
0  CineStar Siam           144

In [ ]:
# ตัวอย่างผลลัพธ์

     branch_name total_tickets
0  CineStar Siam           144

---
### จบ Lab บทที่ 8