<a href="https://colab.research.google.com/github/mxls34/AdvanceDatabase/blob/main/SQL_Test_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

รหัสนักศึกษา:6706021612143

ชื่อ-สกุล:นาย ณัฐกรณ์ มะลิซ้อน

# แบบทดสอบการเขียนคำสั่ง SQL ครั้งที่ 1


จากตาราง Customer เก็บข้อมูลลูกค้า 15 คน ครอบคลุมทุกช่วงอายุและทุกสถานะ โดยมีความไม่สมบูรณ์ของข้อมูลอยู่ในตารางด้วย รายละเอียดของข้อมูลมีดังนี้

* 3 แถว ที่ email เป็น NULL, 1 แถว ที่เป็นค่าว่าง, 2 แถว ที่รูปแบบผิด (ไม่มี @)
* 1 แถว ที่ age เป็น NULL, 2 แถว ที่อายุผิดปกติ (0 และ 150)
* 3 แถว ที่ total_spent เป็น NULL (ยังไม่เคยซื้อของ)
* 5 รูปแบบการสะกด ของ membership_status ที่หมายถึง "active" เหมือนกันแต่เขียนต่างกัน

## Setup

In [1]:
!pip install duckdb --quiet

In [2]:
import duckdb

con = duckdb.connect(database=':memory:')

def run(sql):
    try:
        return con.execute(sql).df()
    except Exception as e:
        print(f"{type(e).__name__}: {e}")

con.execute("""
CREATE TABLE customer (
    customer_id INTEGER, name VARCHAR, email VARCHAR, phone VARCHAR,
    age INTEGER, city VARCHAR, membership_status VARCHAR,
    signup_date DATE, total_spent DECIMAL(10,2)
)
""")
con.executemany("INSERT INTO customer VALUES (?,?,?,?,?,?,?,?,?)", [
    (1, 'มานะ', 'mana@shop.com', '0812345601', 28, 'กรุงเทพฯ', 'active', '2023-01-15', 4500.00),
    (2, 'มานี', None, '0812345602', 34, 'กรุงเทพฯ', 'Active', '2023-02-10', 12300.00),
    (3, 'ปิติ', 'piti.shopmail.com', None, 45, 'เชียงใหม่', 'ACTIVE', '2023-03-05', None),
    (4, 'ชูใจ', 'chujai@shop.com', '0812345604', None, 'เชียงใหม่', 'inactive', '2023-01-20', 890.00),
    (5, 'วีระ', '', '0812345605', 22, 'ชลบุรี', 'active', '2023-04-12', 15600.00),
    (6, 'สมหมาย', 'sommai@shop.com', '', 60, 'ชลบุรี', 'Inactive', '2023-05-01', 320.00),
    (7, 'ดวงตา', 'duangta@shop.com', '0812345607', 0, 'ขอนแก่น', 'active', '2023-02-18', 7800.00),
    (8, 'ประดิษฐ์', None, None, 150, 'ขอนแก่น', 'active', '2023-06-22', None),
    (9, 'เพียงใจ', 'piangjai@shop.com', '0812345609', 31, 'กรุงเทพฯ', 'ACTIVE', '2023-01-30', 2100.00),
    (10, 'สุดสาคร', 'sudsakorn.shop.com', '0812345610', 27, 'ภูเก็ต', 'active', '2023-07-08', 5400.00),
    (11, 'บุญมี', 'boonmee@shop.com', '0812345611', 39, 'ภูเก็ต', 'inactive', '2023-03-14', 990.00),
    (12, 'อารีย์', 'aree@shop.com', '0812345612', 25, 'กรุงเทพฯ', 'active', '2023-08-01', None),
    (13, 'สายัณห์', None, '0812345613', 52, 'สงขลา', 'Active', '2023-02-25', 3200.00),
    (14, 'จันทร์เพ็ญ', 'janpen@shop.com', '0812345614', 19, 'สงขลา', 'active', '2023-09-10', 18900.00),
    (15, 'ทองสุข', 'thongsuk@shop.com', '0812345615', 41, 'เชียงใหม่', 'ACTIVE', '2023-04-28', 6700.00),
])

print("Setup complete — พร้อมเริ่มทำข้อสอบ")

Setup complete — พร้อมเริ่มทำข้อสอบ

In [5]:
run("SHOW TABLES")

       name
0  customer

เขียนคำสั่งดึงข้อมูลในตาราง customer มาแสดง 5 records แรก

In [4]:
# เขียนโค้ดตรงนี้
con.execute(
    "SELECT * FROM customer LIMIT 5"
).df()

,customer_id,name,email,phone,age,city,membership_status,signup_date,total_spent
0,1,มานะ,mana@shop.com,0812345601,28,กรุงเทพฯ,active,2023-01-15,4500.0
1,2,มานี,None,0812345602,34,กรุงเทพฯ,Active,2023-02-10,12300.0
2,3,ปิติ,piti.shopmail.com,None,45,เชียงใหม่,ACTIVE,2023-03-05,NaN
3,4,ชูใจ,chujai@shop.com,0812345604,<NA>,เชียงใหม่,inactive,2023-01-20,890.0
4,5,วีระ,,0812345605,22,ชลบุรี,active,2023-04-12,15600.0

In [ ]:
# ตัวอย่างผลลัพธ์

,customer_id,name,email,phone,age,city,membership_status,signup_date,total_spent
0,1,มานะ,mana@shop.com,0812345601,28,กรุงเทพฯ,active,2023-01-15,4500.0
1,2,มานี,None,0812345602,34,กรุงเทพฯ,Active,2023-02-10,12300.0
2,3,ปิติ,piti.shopmail.com,None,45,เชียงใหม่,ACTIVE,2023-03-05,NaN
3,4,ชูใจ,chujai@shop.com,0812345604,<NA>,เชียงใหม่,inactive,2023-01-20,890.0
4,5,วีระ,,0812345605,22,ชลบุรี,active,2023-04-12,15600.0

---
# Part 1: SELECT & Filtering

**1.1**

In [6]:
# เขียนคำสั่ง SQL ข้อ 1.1 ตรงนี้
run("""
  SELECT name, city, total_spent AS spending FROM customer
""")

          name       city  spending
0         มานะ   กรุงเทพฯ    4500.0
1         มานี   กรุงเทพฯ   12300.0
2         ปิติ  เชียงใหม่       NaN
3         ชูใจ  เชียงใหม่     890.0
4         วีระ     ชลบุรี   15600.0
5       สมหมาย     ชลบุรี     320.0
6        ดวงตา    ขอนแก่น    7800.0
7     ประดิษฐ์    ขอนแก่น       NaN
8      เพียงใจ   กรุงเทพฯ    2100.0
9      สุดสาคร     ภูเก็ต    5400.0
10       บุญมี     ภูเก็ต     990.0
11      อารีย์   กรุงเทพฯ       NaN
12     สายัณห์      สงขลา    3200.0
13  จันทร์เพ็ญ      สงขลา   18900.0
14      ทองสุข  เชียงใหม่    6700.0

In [ ]:
# ตัวอย่างผลลัพธ์ข้อ 1.1

          name       city  spending
0         มานะ   กรุงเทพฯ    4500.0
1         มานี   กรุงเทพฯ   12300.0
2         ปิติ  เชียงใหม่       NaN
3         ชูใจ  เชียงใหม่     890.0
4         วีระ     ชลบุรี   15600.0
5       สมหมาย     ชลบุรี     320.0
6        ดวงตา    ขอนแก่น    7800.0
7     ประดิษฐ์    ขอนแก่น       NaN
8      เพียงใจ   กรุงเทพฯ    2100.0
9      สุดสาคร     ภูเก็ต    5400.0
10       บุญมี     ภูเก็ต     990.0
11      อารีย์   กรุงเทพฯ       NaN
12     สายัณห์      สงขลา    3200.0
13  จันทร์เพ็ญ      สงขลา   18900.0
14      ทองสุข  เชียงใหม่    6700.0

**1.2**

In [39]:
# เขียนคำสั่ง SQL ข้อ 1.2 ตรงนี้
run("""
    SELECT DISTINCT city FROM customer
""")

        city
0   กรุงเทพฯ
1  เชียงใหม่
2     ชลบุรี
3    ขอนแก่น
4     ภูเก็ต
5      สงขลา

In [ ]:
# ตัวอย่างผลลัพธ์ข้อ 1.2

        city
0     ชลบุรี
1    ขอนแก่น
2     ภูเก็ต
3      สงขลา
4   กรุงเทพฯ
5  เชียงใหม่

**1.3**

In [23]:
# เขียนคำสั่ง SQL ข้อ 1.3 ตรงนี้
run("""
  SELECT * FROM customer WHERE total_spent > 5000
""")

,customer_id,name,email,phone,age,city,membership_status,signup_date,total_spent
0,2,มานี,None,0812345602,34,กรุงเทพฯ,Active,2023-02-10,12300.0
1,5,วีระ,,0812345605,22,ชลบุรี,active,2023-04-12,15600.0
2,7,ดวงตา,duangta@shop.com,0812345607,0,ขอนแก่น,active,2023-02-18,7800.0
3,10,สุดสาคร,sudsakorn.shop.com,0812345610,27,ภูเก็ต,active,2023-07-08,5400.0
4,14,จันทร์เพ็ญ,janpen@shop.com,0812345614,19,สงขลา,active,2023-09-10,18900.0
5,15,ทองสุข,thongsuk@shop.com,0812345615,41,เชียงใหม่,ACTIVE,2023-04-28,6700.0

In [ ]:
# ตัวอย่างผลลัพธ์ข้อ 1.3

,customer_id,name,email,phone,age,city,membership_status,signup_date,total_spent
0,2,มานี,None,0812345602,34,กรุงเทพฯ,Active,2023-02-10,12300.0
1,5,วีระ,,0812345605,22,ชลบุรี,active,2023-04-12,15600.0
2,7,ดวงตา,duangta@shop.com,0812345607,0,ขอนแก่น,active,2023-02-18,7800.0
3,10,สุดสาคร,sudsakorn.shop.com,0812345610,27,ภูเก็ต,active,2023-07-08,5400.0
4,14,จันทร์เพ็ญ,janpen@shop.com,0812345614,19,สงขลา,active,2023-09-10,18900.0
5,15,ทองสุข,thongsuk@shop.com,0812345615,41,เชียงใหม่,ACTIVE,2023-04-28,6700.0

**1.4**

In [28]:
# เขียนคำสั่ง SQL ข้อ 1.4 ตรงนี้
run("""
  SELECT * FROM customer ORDER BY total_spent DESC LIMIT 5
""")

,customer_id,name,email,phone,age,city,membership_status,signup_date,total_spent
0,14,จันทร์เพ็ญ,janpen@shop.com,0812345614,19,สงขลา,active,2023-09-10,18900.0
1,5,วีระ,,0812345605,22,ชลบุรี,active,2023-04-12,15600.0
2,2,มานี,None,0812345602,34,กรุงเทพฯ,Active,2023-02-10,12300.0
3,7,ดวงตา,duangta@shop.com,0812345607,0,ขอนแก่น,active,2023-02-18,7800.0
4,15,ทองสุข,thongsuk@shop.com,0812345615,41,เชียงใหม่,ACTIVE,2023-04-28,6700.0

In [ ]:
# ตัวอย่างผลลัพธ์ข้อ 1.4

,customer_id,name,email,phone,age,city,membership_status,signup_date,total_spent
0,14,จันทร์เพ็ญ,janpen@shop.com,0812345614,19,สงขลา,active,2023-09-10,18900.0
1,5,วีระ,,0812345605,22,ชลบุรี,active,2023-04-12,15600.0
2,2,มานี,None,0812345602,34,กรุงเทพฯ,Active,2023-02-10,12300.0
3,7,ดวงตา,duangta@shop.com,0812345607,0,ขอนแก่น,active,2023-02-18,7800.0
4,15,ทองสุข,thongsuk@shop.com,0812345615,41,เชียงใหม่,ACTIVE,2023-04-28,6700.0

---
# Part 2: Complex Conditions

**2.1**

In [37]:
# เขียนคำสั่ง SQL ข้อ 2.1 ตรงนี้
run("""
  SELECT * FROM customer WHERE age BETWEEN 20 AND 40
""")

,customer_id,name,email,phone,age,city,membership_status,signup_date,total_spent
0,1,มานะ,mana@shop.com,0812345601,28,กรุงเทพฯ,active,2023-01-15,4500.0
1,2,มานี,None,0812345602,34,กรุงเทพฯ,Active,2023-02-10,12300.0
2,5,วีระ,,0812345605,22,ชลบุรี,active,2023-04-12,15600.0
3,9,เพียงใจ,piangjai@shop.com,0812345609,31,กรุงเทพฯ,ACTIVE,2023-01-30,2100.0
4,10,สุดสาคร,sudsakorn.shop.com,0812345610,27,ภูเก็ต,active,2023-07-08,5400.0
5,11,บุญมี,boonmee@shop.com,0812345611,39,ภูเก็ต,inactive,2023-03-14,990.0
6,12,อารีย์,aree@shop.com,0812345612,25,กรุงเทพฯ,active,2023-08-01,NaN

In [ ]:
# ตัวอย่างผลลัพธ์ข้อ 2.1

,customer_id,name,email,phone,age,city,membership_status,signup_date,total_spent
0,1,มานะ,mana@shop.com,0812345601,28,กรุงเทพฯ,active,2023-01-15,4500.0
1,2,มานี,None,0812345602,34,กรุงเทพฯ,Active,2023-02-10,12300.0
2,5,วีระ,,0812345605,22,ชลบุรี,active,2023-04-12,15600.0
3,9,เพียงใจ,piangjai@shop.com,0812345609,31,กรุงเทพฯ,ACTIVE,2023-01-30,2100.0
4,10,สุดสาคร,sudsakorn.shop.com,0812345610,27,ภูเก็ต,active,2023-07-08,5400.0
5,11,บุญมี,boonmee@shop.com,0812345611,39,ภูเก็ต,inactive,2023-03-14,990.0
6,12,อารีย์,aree@shop.com,0812345612,25,กรุงเทพฯ,active,2023-08-01,NaN

**2.2**

In [40]:
# เขียนคำสั่ง SQL ข้อ 2.2 ตรงนี้
run("""
    SELECT * FROM customer WHERE city IN('กรุงเทพฯ', 'เชียงใหม่', 'ภูเก็ต')
""")

,customer_id,name,email,phone,age,city,membership_status,signup_date,total_spent
0,1,มานะ,mana@shop.com,0812345601,28,กรุงเทพฯ,active,2023-01-15,4500.0
1,2,มานี,None,0812345602,34,กรุงเทพฯ,Active,2023-02-10,12300.0
2,3,ปิติ,piti.shopmail.com,None,45,เชียงใหม่,ACTIVE,2023-03-05,NaN
3,4,ชูใจ,chujai@shop.com,0812345604,<NA>,เชียงใหม่,inactive,2023-01-20,890.0
4,9,เพียงใจ,piangjai@shop.com,0812345609,31,กรุงเทพฯ,ACTIVE,2023-01-30,2100.0
5,10,สุดสาคร,sudsakorn.shop.com,0812345610,27,ภูเก็ต,active,2023-07-08,5400.0
6,11,บุญมี,boonmee@shop.com,0812345611,39,ภูเก็ต,inactive,2023-03-14,990.0
7,12,อารีย์,aree@shop.com,0812345612,25,กรุงเทพฯ,active,2023-08-01,NaN
8,15,ทองสุข,thongsuk@shop.com,0812345615,41,เชียงใหม่,ACTIVE,2023-04-28,6700.0

In [ ]:
# ตัวอย่างผลลัพธ์ข้อ 2.2

,customer_id,name,email,phone,age,city,membership_status,signup_date,total_spent
0,1,มานะ,mana@shop.com,0812345601,28,กรุงเทพฯ,active,2023-01-15,4500.0
1,2,มานี,None,0812345602,34,กรุงเทพฯ,Active,2023-02-10,12300.0
2,3,ปิติ,piti.shopmail.com,None,45,เชียงใหม่,ACTIVE,2023-03-05,NaN
3,4,ชูใจ,chujai@shop.com,0812345604,<NA>,เชียงใหม่,inactive,2023-01-20,890.0
4,9,เพียงใจ,piangjai@shop.com,0812345609,31,กรุงเทพฯ,ACTIVE,2023-01-30,2100.0
5,10,สุดสาคร,sudsakorn.shop.com,0812345610,27,ภูเก็ต,active,2023-07-08,5400.0
6,11,บุญมี,boonmee@shop.com,0812345611,39,ภูเก็ต,inactive,2023-03-14,990.0
7,12,อารีย์,aree@shop.com,0812345612,25,กรุงเทพฯ,active,2023-08-01,NaN
8,15,ทองสุข,thongsuk@shop.com,0812345615,41,เชียงใหม่,ACTIVE,2023-04-28,6700.0

**2.3**

In [66]:
# เขียนคำสั่ง SQL ข้อ 2.3 ตรงนี้
run("""
    SELECT * FROM customer WHERE email NOT LIKE '%@%' AND email <> ''
""")

,customer_id,name,email,phone,age,city,membership_status,signup_date,total_spent
0,3,ปิติ,piti.shopmail.com,None,45,เชียงใหม่,ACTIVE,2023-03-05,NaN
1,10,สุดสาคร,sudsakorn.shop.com,0812345610,27,ภูเก็ต,active,2023-07-08,5400.0

In [ ]:
# ตัวอย่างผลลัพธ์ข้อ 2.3

,customer_id,name,email,phone,age,city,membership_status,signup_date,total_spent
0,3,ปิติ,piti.shopmail.com,None,45,เชียงใหม่,ACTIVE,2023-03-05,NaN
1,10,สุดสาคร,sudsakorn.shop.com,0812345610,27,ภูเก็ต,active,2023-07-08,5400.0

**2.4**

In [50]:
# เขียนคำสั่ง SQL ข้อ 2.4 ตรงนี้
run("""
    SELECT name, total_spent, CASE
        WHEN total_spent < 1000 THEN 'ลูกค้าทั่วไป'
        WHEN total_spent < 10001 THEN 'ลูกค้าประจำ'
        WHEN total_spent > 10000 THEN 'ลูกค้า VIP'
        ELSE 'ไม่เคยซื้อ'
      END AS customer_tier
    FROM customer
""")

          name  total_spent customer_tier
0         มานะ       4500.0   ลูกค้าประจำ
1         มานี      12300.0    ลูกค้า VIP
2         ปิติ          NaN    ไม่เคยซื้อ
3         ชูใจ        890.0  ลูกค้าทั่วไป
4         วีระ      15600.0    ลูกค้า VIP
5       สมหมาย        320.0  ลูกค้าทั่วไป
6        ดวงตา       7800.0   ลูกค้าประจำ
7     ประดิษฐ์          NaN    ไม่เคยซื้อ
8      เพียงใจ       2100.0   ลูกค้าประจำ
9      สุดสาคร       5400.0   ลูกค้าประจำ
10       บุญมี        990.0  ลูกค้าทั่วไป
11      อารีย์          NaN    ไม่เคยซื้อ
12     สายัณห์       3200.0   ลูกค้าประจำ
13  จันทร์เพ็ญ      18900.0    ลูกค้า VIP
14      ทองสุข       6700.0   ลูกค้าประจำ

In [ ]:
# ตัวอย่างผลลัพธ์ข้อ 2.4

          name  total_spent customer_tier
0         มานะ       4500.0   ลูกค้าประจำ
1         มานี      12300.0    ลูกค้า VIP
2         ปิติ          NaN    ไม่เคยซื้อ
3         ชูใจ        890.0  ลูกค้าทั่วไป
4         วีระ      15600.0    ลูกค้า VIP
5       สมหมาย        320.0  ลูกค้าทั่วไป
6        ดวงตา       7800.0   ลูกค้าประจำ
7     ประดิษฐ์          NaN    ไม่เคยซื้อ
8      เพียงใจ       2100.0   ลูกค้าประจำ
9      สุดสาคร       5400.0   ลูกค้าประจำ
10       บุญมี        990.0  ลูกค้าทั่วไป
11      อารีย์          NaN    ไม่เคยซื้อ
12     สายัณห์       3200.0   ลูกค้าประจำ
13  จันทร์เพ็ญ      18900.0    ลูกค้า VIP
14      ทองสุข       6700.0   ลูกค้าประจำ

**2.5**

In [51]:
# เขียนคำสั่ง SQL ข้อ 2.5 ตรงนี้
run("""
    SELECT * FROM customer WHERE (age > 30 OR membership_status = 'active') AND city = 'กรุงเทพฯ'
""")

,customer_id,name,email,phone,age,city,membership_status,signup_date,total_spent
0,1,มานะ,mana@shop.com,0812345601,28,กรุงเทพฯ,active,2023-01-15,4500.0
1,2,มานี,None,0812345602,34,กรุงเทพฯ,Active,2023-02-10,12300.0
2,9,เพียงใจ,piangjai@shop.com,0812345609,31,กรุงเทพฯ,ACTIVE,2023-01-30,2100.0
3,12,อารีย์,aree@shop.com,0812345612,25,กรุงเทพฯ,active,2023-08-01,NaN

In [ ]:
# ตัวอย่างผลลัพธ์ข้อ 2.5

,customer_id,name,email,phone,age,city,membership_status,signup_date,total_spent
0,1,มานะ,mana@shop.com,0812345601,28,กรุงเทพฯ,active,2023-01-15,4500.0
1,2,มานี,None,0812345602,34,กรุงเทพฯ,Active,2023-02-10,12300.0
2,9,เพียงใจ,piangjai@shop.com,0812345609,31,กรุงเทพฯ,ACTIVE,2023-01-30,2100.0
3,12,อารีย์,aree@shop.com,0812345612,25,กรุงเทพฯ,active,2023-08-01,NaN